### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by loicbenoit** [derricksmith/phpsaml#1]
Installation failed, DB was not created.
I had to unsinstall manually in DB (plugins.state = 0) and remove the plugins/phpsaml directory.

GLPI 9.3.1

I'm interested in your plugin anyway. Beside that installation hickup, how stable would you consider your plugin to be?

**Comment by loicbenoit** [comment]
Sorry, my file ownership were wrong and prevented the script from properly executing.
So, I guess, the only question is: How stable would you consider your plugin to be?

**Comment by derricksmith** [comment]
I’ve been using it in production since before I published on Github.  Maybe 6 months so far and I haven’t run into any issues. I don’t run very many other plugins so I haven’t been able to test much beyond my use case.  More testing with other plugins would be helpful.
