### ISSUE TITLE
where to find the updated version

### ISSUE THREAD

**Issue by Mamadou-ly-artp** [derricksmith/phpsaml#104]
hello i am seing that the version 1.2.1 is available but i only see 1.2.0 in the github release page where can i find the updates ?

**Comment by derricksmith** [comment]
I haven't created a release yet for 1.2.1 since there are pending updates to the branch.  You can download the code from the branch though.

**Comment by Mamadou-ly-artp** [comment]
Thanks for your reply
i used this in order to solve my problem

https://github.com/derricksmith/phpsaml/issues/86#issuecomment-1184467184
