### ISSUE TITLE
[SUGGESTION] Add logout redirect option to setup instructions on the README

### ISSUE THREAD

**Issue by gljones2001** [derricksmith/phpsaml#109]
I found a neat option in the Microsoft Azure AD config page that lets Azure AD redirect back to GLPI after an SSO logout. Currently, without this option, when you logout, the page just ends at a message saying "You are logged out."\

However, if you add the option as shown in the image below, using the root URL of GLPI, it goes back to the GLPI login page after a logout and makes the logout just that little bit nicer and smoother. I think it would be a great option to add to the setup instructions.

![image](https://user-images.githubusercontent.com/20365116/194597586-5eba6e1d-488c-4547-bba6-d6fcace08dc2.png)

**Comment by derricksmith** [comment]
Added to 1.2.1 documentation.
