### ISSUE TITLE
Unable to upload documents in GLPI when SAML is enable

### ISSUE THREAD

**Issue by ilicilho** [derricksmith/phpsaml#123]
We discovery a interesting think. 
When SAML Plugin is enable, the feature Document Manager from GLPI works with limitations. Example
When upload a document, the page /front/document.form.php keeps in blank screen.
In apache logs I see: 

`PHP Warning:  Declaration of PluginPhpsamlConfig::showForm() should be compatible with CommonDBTM::showForm($ID, array $options = Array) in /var/www/glpi/plugins/phpsaml/inc/config.class.php on line 53, referer: https://mydomain/front/document.form.php`

I see that the folder is created in GLPI structure, the file are sended to this folder but the error is when the document.form is inserting DB informations because this document is not "saved" on DB but is present in /var/www/glpi/files/xpto....

**Comment by DonutsNL** [comment]
Hi ilicilho,

What glpi and phpsaml versions are you using? 
Are you enforcing phpSaml?

**Comment by ilicilho** [comment]
Hi @DonutsNL 
The phpSAML is 1.1.3 and GLPI is 10.0.6.
I´m not enforcing phpSAML

**Comment by DonutsNL** [comment]
Hi Ilicilho,

Please consider updating to the latest version: https://github.com/derricksmith/phpsaml/releases/tag/1.2.1

**Comment by ilicilho** [comment]
Thanks @DonutsNL , I´ll do this.
