### ISSUE TITLE
Multi PHPSAML Connection

### ISSUE THREAD

**Issue by Aghiles-S** [derricksmith/phpsaml#141]
Can we make a multi connection with phpsaml??

**Comment by DonutsNL** [comment]
This is currently not supported.

**Comment by DonutsNL** [comment]
How many parallel sources would you require?

**Comment by Aghiles-S** [comment]
3 Azure ADs, I tried modifying the PHPSAML plugin to create a similar plugin with a different name. I installed and activated it, but when I try to connect to the second one (another Azure AD), it doesn't work. When I activate only one of them, it works, but when both are active simultaneously, it only takes one configuration. Both redirect me to the first URL

**Comment by Aghiles-S** [comment]
with a different database

**Comment by DonutsNL** [comment]
Hi, as you noticed, renaming the plugin will not work because all everything needs to be renamed including the config tables, queries, namespaces, etc. 

Ill investigate what is needed to support multiple sources. This is allot of work so dont expect a solutions soon.

**Comment by DonutsNL** [comment]
- We can use the Glpi\CommonDropdown object to allow multiple configurations.
- Each configuration will need to add an unique button on the login page. We prob need to rework this UI to support multiple buttons without cluttering the page. (keep it friendly).
- We need to find the correct config ID by matching some unique field like saml_idp_entity_id;
- We need to rework the phpsaml class to be able to handle multiple configurations
- We need to rework the config class to be used as Dropdown.form using the CommonDropdown::showform (guessed to be verified);
- We need to rework the acs class to handle the auth using the correct config based provided by matching the saml_idp_entity_id;
- We need to be able to test this, currently I only have one identity provider. Maybe we can simulate the SAML requests as some sort of smoketest.

Prob can use some help finding a change strategy given the scope of changes. maybe start developing the SAML test.

**Comment by DonutsNL** [comment]
@derricksmith can you add the new feature flag?

**Comment by DonutsNL** [comment]
Maybe consider https://samltest.id/ for testing purposes.
