### ISSUE TITLE
Blank Config Form

### ISSUE THREAD

**Issue by Rob171X** [derricksmith/phpsaml#158]
Hello,

I am new to GLPI so I am trying to see what the issue here might be.  I renamed and copied the extracted folder into the plugins folder and the plugin shows up and installs no errors.  However, whenever I try to set the config the config form shows up as a blank screen.  This is the form at https://<Server name>/plugins/phpsaml/front/config.php

I am using the newest version that was linked a couple of days ago, 06-January I believe, v1.3.  Any help would be appreciated.

Server is Windows Server, GLPI version is 10.0.11

**Comment by DonutsNL** [comment]
Hi @Rob171X ,

Please use the version in my personal repository for the time being. Derrick is in the progress of merging all the changes after being away for some time. You can find my repository here: https://github.com/DonutsNL/phpsaml

**Comment by DonutsNL** [comment]
@Rob171X 

Could you provide us with some feedback on the issue. Did the latest version resolve your issues? 

Rgrds,

**Comment by Rob171X** [comment]
I got it installed but I had the same issue when I click to setup the https:///plugins/phpsaml/front/config.php is still just a blank page.

**Comment by DonutsNL** [comment]
Could you share any error reported in files/_log/phperrors.log regarding the config page?

**Comment by Rob171X** [comment]
Attached are the only log entries I found and I attached a screenshot just for reference of what is happening.  I believe I forgot to mention last time, we are on a closed network with no internet access.

![config_php_page](https://github.com/derricksmith/phpsaml/assets/114008822/569d5a52-1cfa-41d2-8573-e901cf8d6593)
[Logs.txt](https://github.com/derricksmith/phpsaml/files/13924077/Logs.txt)

**Comment by DonutsNL** [comment]
Hi @Rob171X 
Thats interesting. An DNS issue is preventing the the config from retrieving the online version in a nested function. As a result its not returning an array to the nested function that expects nothing else and breaking the whole config page as an result. I split the two nested function, that (if im correct) should now no longer break the config page.

I updated my repository with the fix.

**Comment by Rob171X** [comment]
![config_php_page](https://github.com/derricksmith/phpsaml/assets/114008822/1651533b-7a73-46ff-9424-99fbd2a038d2)
[Logs.txt](https://github.com/derricksmith/phpsaml/files/13924416/Logs.txt)

The form came up partially but there are no labels and the pull down menus don't work.  I appreciate the help.  We are being sent home due to winter weather so I won't be back in the office to test again until Tuesday most likely.

**Comment by DonutsNL** [comment]
Hi @Rob171X,

That means that the database entries from the config where not installed properly. Im not sure why the database wasnt installed, my guess is that there is stuff from an older version in the database or that the version issue also prevented the install from being performed correctly. 

Usually reinstalling the latest plugin fixes the problem. If you had a working configuration already, do manually back it up for later reference. The latest version from my repository addresses allot of database issues but the altered install logic needs a clean install to do so. If this doesnt fix it, please review the log again on why the insert statements during install are failing in your environment.

**Comment by Rob171X** [comment]
I wiped out the plugins portion of the database and reinstalled and that fixed the issue.  I haven't implemented before so no previous config we just started trying to set this up.  Thank you for your help the form is displaying properly now.

**Comment by DonutsNL** [comment]
Your most welcome 🫡. Please close the issue if this fixed it for you. Rgrds Donuts
