### ISSUE TITLE
Since update phpsaml 1.3.0 : loop with Plugin Enforced option

### ISSUE THREAD

**Issue by REMY31470** [derricksmith/phpsaml#159]
Hello,

I'm new to posting but I've always managed to find what I'm looking for in discussion forums. But this time I can't find what I'm looking for, so I've come up with this problem.

Loop during microsoftonline login.

With phpsaml version 1.2.1 : it is functional with version 10.0.10 of GLPI
On the other hand, if I wish to pass in 10.0.11 it is necessary that I pass in version 1.3.0 to correct the blocking of the white page.

But when I upgrade to version 1.3.0, whether it's GLPI version 10.0.10 or even the new version 10.0.11, I get a Token loop every second :

URL visible from the web browser :
https://login.microsoftonline.com/**ID of the resource tenant**/saml2?SAMLRequest=***Token1**
https://login.microsoftonline.com/**ID of the resource tenant**/saml2?SAMLRequest=***Token2**
https://login.microsoftonline.com/**ID of the resource tenant**/saml2?SAMLRequest=***Token3**
...

In the user connection logs on our Tenant 365, we find our access attempts with the status "Operation successful" for the published application but every second we have a new one, then a new one, then ....

When we indicate **No** in the **Plugin Enforced** section and on the home page we click on the phpSaml button, it works.
So it's when we set the auto login to mandatory that it doesn't work any more and we end up with a page that runs in a loop with a series of tokens that change every second in the URL link.

Thanks in advance for your help and feedback on this subject.
Have a nice day!
Rémy

**Comment by DonutsNL** [comment]
Hi @REMY31470 

Thanks for your feedback. This is an issue also reported in another thread. I have been debugging this and found the issue. I will push the update this evening.

Rgrds,

**Comment by DonutsNL** [comment]
I found an issue in the excludes logic and corrected it.  The return was incorrectly included in the foreach loop and always returned false after the first itteration as an result. I corrected the typo.

**Comment by REMY31470** [comment]
Hi @DonutsNL ,

Thank you very much, the auto login is working correctly.
And thank you for your quick action.

Rgrds,

**Comment by DonutsNL** [comment]
Your most welcome. Thanks for reporting the issue and helping us improving the plugin.
