### ISSUE TITLE
Your XML

### ISSUE THREAD

**Issue by orthagh** [derricksmith/phpsaml#16]
Hello @derricksmith 

I'm currently reviewing your plugin submission on GLPI Plugin catalog.

Here is some issues to fix before i accept the plugin:

- tag a version and create a release archive (it's not a good practice to send an archive of master branch)
- Add a `screenshots` tags into your xml. It seems you already have screenshots in your repository, it should be easy to add them.
  Ex : https://github.com/pluginsGLPI/mreporting/blob/master/mreporting.xml#L210-L219

After that, we'll be happy to accept your plugin.

Regards

**Comment by derricksmith** [comment]
Done, thanks!

**Comment by orthagh** [comment]
Plugin accepted, it should pop into plugins catalog in some minutes
