### ISSUE TITLE
GLPI 10.0.12 --> Error 500 on plugin page

### ISSUE THREAD

**Issue by VF404** [derricksmith/phpsaml#163]
Hello,

Since I've update my GLPI to 10.0.12, when I click on "Plugins" on left side bar, I have an error 500.
Maybe @DonutsNL your fork is not update for 10.0.12 version ?

Thanks for you help.

**Comment by VF404** [comment]
In my php-errors.log I have :

[2024-02-05 21:59:30] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot redeclare plugin_version_phpsaml() (previously declared in /var/www/html/glpi/plugins/phpsaml.bak/setup.php:61) in /var/www/html/glpi/plugins/phpsaml/setup.php at line 56  
[2024-02-05 21:59:54] glpiphplog.WARNING:   *** PHP User Warning (512): plugin_version_phpsaml.bak method must be defined! in /var/www/html/glpi/src/Plugin.php at line 1810
  Backtrace :
  src/Plugin.php:1810                                trigger_error()
  src/Plugin.php:1848                                Plugin::getInfo()
  src/Plugin.php:517                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:786                                 Plugin->getPluginInformation()
  src/Plugin.php:570                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:505                                 Plugin->checkPluginState()
  front/plugin.php:43                                Plugin->checkStates()
  public/index.php:82                                require()

**Comment by ChrisGralike** [comment]
Hi @Loopers29 

You cannot keep the backup inside the GLPI plugins folder. The subfolders are indexed by GLPI and this causes naming issues in the files loaded by default (like setup.php). Move the backup version of the plugin away from the glpi/plugin installation.

**Comment by VF404** [comment]
Yes thanks ! It works but now, with same certificate and input, I have now this error : 
![image](https://github.com/derricksmith/phpsaml/assets/55393114/8c1f4ccb-470b-4da5-969d-0359145c2b07)

**Comment by DonutsNL** [comment]
Enable or disable (toggle) the message and response compression in the settings in the config.class.php.

**Comment by VF404** [comment]
I did this : 
    public const CMPREQ     = true; // Compress requests
    public const CMPRES     = true; // Compress response
but I have now this : 
<img width="621" alt="Screenshot 2024-02-06 at 09 50 55" src="https://github.com/derricksmith/phpsaml/assets/55393114/f56eeb9a-81b8-4d35-8014-97676631032b">

**Comment by VF404** [comment]
It's now a duplicate ticket of [#161](https://github.com/derricksmith/phpsaml/issues/161) and [#164](https://github.com/derricksmith/phpsaml/issues/164) so I'm closing this one and following one of them.
Thanks for your help !
