### ISSUE TITLE
Typo in SQL column name for setup

### ISSUE THREAD

**Issue by bbalet** [derricksmith/phpsaml#2]
The column name should be `debug` and not `degub`

    INSERT INTO `glpi_plugin_phpsaml_configs`
                     (`id`, `strict`, `degub`, `saml_idp_entity_id`, `saml_sp_certificate`, `saml_sp_certificate_key`, 
    `saml_idp_single_sign_on_service`, `saml_idp_single_logout_service`, `saml_idp_certificate`)
                VALUES
                     ('1', '', '', '', '', '', '', '', '')

**Comment by derricksmith** [comment]
I just updated.  Thanks
