### ISSUE TITLE
Base URL with subfolder

### ISSUE THREAD

**Issue by bvessey** [derricksmith/phpsaml#22]
When using a base url such as https://example.com/glpi a successful login is directed to https://example.com/glpi/glpi/front/central.php instead of https://example.com/glpi/front/central.php

This issue doesn't happen if accessing via a virtual server hosting the glpi instance directly at https://example.com

SAML / SSO with Azure AD.

**Comment by derricksmith** [comment]
As of the current release, hosting glpi in a subdirectory is not supported.  I believe this will be a relatively easy modification but need to address bugfixes in release 1.1.0 before I can add this feature.

**Comment by derricksmith** [comment]
I standardized the URLs and removed some extra concatenation that I beleive was causing your problem.  Can can you check if PR #55 fixes your issue?

**Comment by bvessey** [comment]
I'd love to help but I've had to disable all external access to glpi, so without an internet-facing login I'm dead in the water.  Sorry

**Comment by derricksmith** [comment]
Thanks for your response.  I've tested in my dev environment with no adverse impact.  I'll consider this closed.  Thanks
