### ISSUE TITLE
How to connect with local database GLPI after sso activated?

### ISSUE THREAD

**Issue by orlandotnras** [derricksmith/phpsaml#23]
Hello,

How to connect with local database GLPI after sso activated?because donc user with superadmin acces

**Comment by orlandotnras** [comment]
index.php?noAUTO=1 don't work

**Comment by derricksmith** [comment]
There is currently no backdoor for local login when this plugin is enabled.  It would be easy enough to implement with an arbitrary $_GET variable in setup.php.  I'm slammed at work right now and don't have time to implement and test but could work on it towards the end of December.  Open to pull requests if you want to contribute.

**Comment by derricksmith** [comment]
This feature was added in Release 1.1.0.  There is a configuration option to enforce the plugin.  When this option is set to "No", users are directed to the GLPI login page and can login directly or select "Login with SSO".  When the option is  set to "Yes" all logins will be directed to SSO.

**Comment by mklimasz5** [comment]
Hi Derrick

Thanks for Your help!

Just tested the new version and I couldn't get it to work. Service provider data remains the same (plugin configuration), so nothing is lost, login page is definitely enhanced with standard login options and a button "Login with SSO" (plugin is in non-enforcing mode), but then there is no redirection to SSO provider. Also, under the plugin configuration - I don't know if I'm setting the Security part right, as it defaults to "Better" and none of the provided options can be added to "Selected" (after Update button is pressed all returns to previous state). Perhaps I'm doing something wrong, yet version 1.0.0 works perfectly for me...
