### ISSUE TITLE
AADSTS50011: The reply URL specified in the request does not match

### ISSUE THREAD

**Issue by hyag-afk** [derricksmith/phpsaml#24]
Hello, 

I'm Hyag. I made the configuration mentioned in the site Reply URL (Assertion Consumer Service URL) = {Your GLPI web server base URL} /front/acs.php and I have this error AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application.

Best regards,

**Comment by Tom74FR** [comment]
Hello. Same issue for me. Do you find the solution?
Regards
Thomas

**Comment by derricksmith** [comment]
Send a screenshot of your config?  Obfuscate domain in the urls and the certs

**Comment by DjavanRoa** [comment]
Hi,
Same error here :(
Followed the readme instructions but sill a bit confused by a couple hiccups.
Doc did not say the pluggin had to rely in a folder exlicitly named/renamed "phpsaml" to be detected.
For "SP Certificate" do I have to generate à new certificat or does it have to be the same as the one used for the web service ? (I'm using a wildcard cert)
If I open a tab to https://myserver.domain.com/front/acs.php I get a "Not found. The requested URL /front/acs.php was not found on this server." is this expected ?

On AzureAD I've declared a new "Enterprise Application", added current user member role, under Single sign-on enabled SAML with these settings :
Identifier (Entity ID) : https://myserver.domain.com/
Reply URL (Assertion Consumer Service URL) : https://myserver.domain.com/front/acs.php
+ copied cert & URLs to glpi

When testing opening glpi URL I get promped for AzureAD login, I see the login attempt succed in AzureAD sign-ins logs, then AzureAD throws this error : "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'https://myserver.domain.com/'."

Still don't get what I'm doing wrong, any hints ? :-)

Regards,

**Comment by DjavanRoa** [comment]
Ok I think I got it working by changing the reply ACS url in the AzureAD application to:
Reply URL (Assertion Consumer Service URL) : https://myserver.domain.com/plugins/phpsaml/front/acs.php

**Comment by Tom74FR** [comment]
Thanks
I confirm that with
https://myserver.domain.com/plugins/phpsaml/front/acs.php this is well
working.
Thomas


Le ven. 13 nov. 2020 à 12:16, Djavan ROA <notifications@github.com> a
écrit :

**Comment by derricksmith** [comment]
> 
> 
> Ok I think I got it working by changing the reply ACS url in the AzureAD application to:
> Reply URL (Assertion Consumer Service URL) : https://myserver.domain.com/plugins/phpsaml/front/acs.php
> 
> If this helps anyone:
> I used https://www.samltool.com/decode.php to decode the SAML request sent to AzureAD, I found the expected "AssertionConsumerServiceURL" property in the XML body and used that as reply URL on AzureAD.

Thanks for this.  I'll update the readme.
