### ISSUE TITLE
Problem with fusioninvetory after install SSO

### ISSUE THREAD

**Issue by orlandotnras** [derricksmith/phpsaml#25]
After install SSO all is ok but fusioninventory URL is redirected directlty with sso too

**Comment by pablitobin** [comment]
same!

**Comment by orlandotnras** [comment]
i would to rewrite NTLMAuth off for fusioninventory but i don't find where in the code

**Comment by derricksmith** [comment]
Line 147 of setup.php controls allowing FusionInventory.  You'll need to see what is different in your environments to understand why this code is not executing.

if (class_exists('PluginFusioninventoryCommunication') && strpos($_SERVER['HTTP_USER_AGENT'], 'FusionInventory-Agent_')){ 
			if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory/')){
				return;
			}
		}

**Comment by orlandotnras** [comment]
all is ok for variable environements but don't work fusioninvetory

**Comment by orlandotnras** [comment]
i don't fix this

**Comment by pablitobin** [comment]
me neither

**Comment by derricksmith** [comment]
Are you both running GLPI on Windows?

**Comment by pablitobin** [comment]
yes

**Comment by derricksmith** [comment]
You don't need to disable/reenable.

**Comment by pablitobin** [comment]
If I change it, glpi crashed... error http500

**Comment by derricksmith** [comment]
Line 148 should read:

if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory\')){

**Comment by pablitobin** [comment]
yes, but it does not work. GLPI crashes. glpi does not crash if we use / or without slash but if I add this slash \, it crashed.

**Comment by derricksmith** [comment]
Duh, I should have put it into an ide before sending.  We have to escape the slash when in front of a quote.  The line should read:

if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory\\')){

**Comment by pablitobin** [comment]
What is the difference with your first comment to switch / with \ and this
line?
I copied and paste that one and it crashed again.

**Comment by derricksmith** [comment]
I edited after...there are two \\.  You have to escape the backslash when in front of a quote

**Comment by derricksmith** [comment]
`if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory\\')){`

**Comment by pablitobin** [comment]
still same behaviur. If I disable plugin, computer agent can connect to
glpi and report/inventory.. If I enable plugin, no connection.

**Comment by pablitobin** [comment]
I noticed that If i try to access the fusioninventory service url (xxxx/plugins/fusioninventory), when SAML is enabled, I get a "redirection failed" but I disabled it, it works.

**Comment by pablitobin** [comment]
I remove the HTTP_USER_AGENT condition (line 147) and it works. For some reason that "condition" is not working. But it should: http://fusioninventory.org/documentation/security.html

**Comment by orlandotnras** [comment]
No not windows, i am on debian

**Comment by orlandotnras** [comment]
> I remove the HTTP_USER_AGENT condition (line 147) and it works. For some reason that "condition" is not working. But it should: http://fusioninventory.org/documentation/security.html

You remove HTTP_USER_AGENT?? all line or only variable?

**Comment by pablitobin** [comment]
Remove the condition, the line should read:

if (class_exists('PluginFusioninventoryCommunication')){

**Comment by derricksmith** [comment]
We need the user agent clause, otherwise normal web requests to /plugins/fusioninventory/ will bypass SSO.  I'm troubleshooting on my dev system and should have an answer today.

**Comment by pablitobin** [comment]
Yes, it is correct but it is working as workaround. 
Regarding FusionInventory site:
![image](https://user-images.githubusercontent.com/40396227/98961404-25702680-24cb-11eb-9699-ba617c84c287.png)

Should not be : **FusionInventory-Agent_v**    ?
Line 147 just appears as (without "_v" at the end: 
if (class_exists('PluginFusioninventoryCommunication') && strpos($_SERVER['HTTP_USER_AGENT'], **'FusionInventory-Agent_'**)){

**Comment by derricksmith** [comment]
strpos is currently set to 'FusionInventory-Agent_' which matches any agent. My Apache logs show:

[12/Nov/2020:06:37:49 +0000] "POST /plugins/fusioninventory/ HTTP/1.1" 200 4320 "-" "FusionInventory-Agent_v2.5.2"

strpos 'FusionInventory-Agent_' on FusionInventory-Agent_v2.5.2 matches

![image](https://user-images.githubusercontent.com/7143479/98963922-6f560e00-24c5-11eb-8b7a-d9d55a74ec3c.png)

Can you look at your webserver access logs and post the connect attempt for fusion-inventory?

**Comment by pablitobin** [comment]
[12/Nov/2020:09:58:31 -0600] "GET /gl/agents-fusion//fusioninventory-agent_windows-x64_2.5.2.exe HTTP/1.1" 200 10098308

**Comment by pablitobin** [comment]
[12/Nov/2020:10:45:21 -0600] "POST /gl/plugins/fusioninventory/ HTTP/1.1" 200 99

**Comment by derricksmith** [comment]
There's no user agent in the request.  Do you see user agents in any other requests in the logs?  For example, this is what I show for regular browsers accessing the site:

[12/Nov/2020:16:48:10 +0000] "GET /ajax/displayMessageAfterRedirect.php HTTP/1.1" 200 1027 "https://xxxxxxxxx/front/marketplace.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"

**Comment by pablitobin** [comment]
I think that my agents are doing HTTP requests. Because they are working. If I need to force an inventory, I login to http://localhost:62354/ and I can force an Inventory after it finishes, I got data on "Computers" in GLPI.
![image](https://user-images.githubusercontent.com/40396227/98971703-2018d900-24d7-11eb-9748-1a18a3f44728.png)

![image](https://user-images.githubusercontent.com/40396227/98971808-43438880-24d7-11eb-9c97-9e4d806e5a76.png)

**Comment by pablitobin** [comment]
[11/Nov/2020:20:59:49 -0600] "GET /gl/pics/favicon.ico HTTP/1.1" 200 4286
[11/Nov/2020:20:59:49 -0600] "GET /gl/plugins/timezones/ajax/tz.php?_=1605149988808 HTTP/1.1" 200 38
[11/Nov/2020:20:59:49 -0600] "GET /gl/plugins/mydashboard/scripts/mydashboard.js?v=1.7.7 HTTP/1.1" 200 1572

**Comment by pablitobin** [comment]
Could it be because we are using Application Proxy (Azure)? We use App Proxy + Single Sign On
![image](https://user-images.githubusercontent.com/40396227/98972643-53a83300-24d8-11eb-9abb-7c30005a3c84.png)

**Comment by derricksmith** [comment]
Okay, thanks for the additional info.  What webserver are you running? There has to be a user agent, I just think it isn't displayed in your logs.  

Its possible there is an issue with Application Proxy, I'm not familiar with it but I'll do some research.

**Comment by pablitobin** [comment]
Apache

**Comment by derricksmith** [comment]
I think that is the problem.  From the logs, it doesn't look like the proxy is passing a user agent to apache but the app proxy documentation says it does forward HTTP headers.

![image](https://user-images.githubusercontent.com/7143479/98976717-ee067780-24d4-11eb-9c2f-29936d700e22.png)

You may need to add a log format to your apache config so we can get more info about the request.
https://serverfault.com/questions/888151/apache-doesnt-log-remoteip-when-remoteipheader-x-forwarded-for-is-present

**Comment by derricksmith** [comment]
FYI, in my apache2.conf here is my LogFormat settings:

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

in my virtualhost:

ErrorLog ${APACHE_LOG_DIR}/glpi/error.log
CustomLog ${APACHE_LOG_DIR}/glpi/access.log combined

**Comment by pablitobin** [comment]
same result.. all logs with HTTP/1.1

**Comment by FWITC** [comment]
i use Ubuntu 20.04 and Nginx Webserver my Clients got the Message

The Fusion Inventory Agend Log shows that Microsoft page is opened. also with the if (class_exists('PluginFusioninventoryCommunication')){ modification.

**Comment by FWITC** [comment]
with this code i solved the problem.

 if (strpos($_SERVER['REQUEST_URI'], 'front/logout.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\logout.php') !== false ){
                $_SESSION['noAUTO'] = 1;
        }

        if (!empty($config['saml_idp_entity_id']) && !empty($config['saml_idp_single_sign_on_service']) && !empty($config['saml_idp_certificate'])){
                $phpsaml = new PluginPhpsamlPhpsaml();
                if (strpos($_SERVER['REQUEST_URI'], 'front/cron.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\cron.php') !== false){
                        return;
                }

                if (strpos($_SERVER['REQUEST_URI'], 'apirest.php') !== false){
                        return;
                }

                if (strpos($_SERVER['REQUEST_URI'], 'front/acs.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\acs.php') !== false){
                        return;
                }

                if (class_exists('PluginFusioninventoryCommunication') && strpos($_SERVER['HTTP_USER_AGENT'], 'FusionInventory-Agent_') !== false){
                        if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') !== false || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory' !== false)){
                                return;
                        }
                }

                if (strpos($_SERVER['REQUEST_URI'], 'front/logout.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\logout.php') !== false){
                        if (!empty($config['saml_idp_single_logout_service'])){
                                $phpsaml::sloRequest();
                        }
                }

**Comment by derricksmith** [comment]
> with this code i solved the problem.
> 
> if (strpos($_SERVER['REQUEST_URI'], 'front/logout.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\logout.php') !== false ){
> $_SESSION['noAUTO'] = 1;
> }
> 
> ```
>     if (!empty($config['saml_idp_entity_id']) && !empty($config['saml_idp_single_sign_on_service']) && !empty($config['saml_idp_certificate'])){
>             $phpsaml = new PluginPhpsamlPhpsaml();
>             if (strpos($_SERVER['REQUEST_URI'], 'front/cron.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\cron.php') !== false){
>                     return;
>             }
> 
>             if (strpos($_SERVER['REQUEST_URI'], 'apirest.php') !== false){
>                     return;
>             }
> 
>             if (strpos($_SERVER['REQUEST_URI'], 'front/acs.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\acs.php') !== false){
>                     return;
>             }
> 
>             if (class_exists('PluginFusioninventoryCommunication') && strpos($_SERVER['HTTP_USER_AGENT'], 'FusionInventory-Agent_') !== false){
>                     if(strpos($_SERVER['REQUEST_URI'], '/plugins/fusioninventory/') !== false || strpos($_SERVER['REQUEST_URI'], '\plugins\fusioninventory' !== false)){
>                             return;
>                     }
>             }
> 
>             if (strpos($_SERVER['REQUEST_URI'], 'front/logout.php') !== false || strpos($_SERVER['REQUEST_URI'], 'front\logout.php') !== false){
>                     if (!empty($config['saml_idp_single_logout_service'])){
>                             $phpsaml::sloRequest();
>                     }
>             }
> ```

I added these changes in release 1.1.0.

**Comment by derricksmith** [comment]
I believe this is issue is now resolved in 1.1.0.  If I am wrong, please let me know and I will reopen.
