### ISSUE TITLE
Azure AD - Reply URL error

### ISSUE THREAD

**Issue by bnesson** [derricksmith/phpsaml#29]
Hi, 

I'm trying to configure the plugin with azure ad and I get the following error : 
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application

The reply url configured in azure ad is https://glpitest.xxxx.com/plugins/phpsaml/front/acs.php

I'd like to know what is the reply url sent by GLPI so I've activated debug in the plugin, is there a log file where I can see this URL?

Thanks for your help

**Comment by derricksmith** [comment]
acs.php will log to glpi_root/files/_logs/php-errors.php

I've updated release 1.1.0 to output the error to screen also.

**Comment by christianlx** [comment]
Hi, 
I have a same issue after the configuration of SAM in AAD. I setup the connection with the readme but there's a problem with the reply. I setup the connection URL to https://glpi.xxxx.com and the reply address to https://glpi.xxx.com/plugins/phpsaml/front/acs.php When I login using SSO, I have the message AADSTS50011 : The reply URL specified in the request does not match the reply URLs configured for the application : http://glpi.xxxx.com 

So the request ask a non secure http that I can't add in the list of reply adresses in SAML configuration (button greyed out without a "s"). I don't have error in the php-errors on linux side. If you have an idea ?

**Comment by derricksmith** [comment]
Confirm your IdP configuration in Azure.

**Comment by christianlx** [comment]
I'm not a specialist of AAD but here's the config I did : 
in Entreprise applications, creation of a SAML : 
![glpi-saml1](https://user-images.githubusercontent.com/10811230/112503093-f035e800-8d8a-11eb-8a37-a59e33546e9a.jpg)
It generate the following url : 
![glpi-saml2](https://user-images.githubusercontent.com/10811230/112503226-080d6c00-8d8b-11eb-873d-2f37502eb27f.jpg)
I copy them in the plugin configuration : 
![glpisaml3](https://user-images.githubusercontent.com/10811230/112503612-5b7fba00-8d8b-11eb-9ddc-bd8b5da881eb.jpg)

Is there something else to do ?

**Comment by derricksmith** [comment]
Your configuration looks correct but the error you provided does not match your AAD configuration.  The only difference between my configuration and yours is I left "Sign on URL" as optional.

Otherwise, can you confirm your GLPI is setup with HTTPs in your webserver and there is an appropriate redirect for HTTP to HTTPS?

**Comment by christianlx** [comment]
Problem is the same if I let "sign on URL" as an option. There is a redirection http to https on the Web server and it's working fine.
So no idea for the moment.

**Comment by derricksmith** [comment]
Is this still an issue, were you able to run SAMLTracer?

**Comment by christianlx** [comment]
I have still the issue. I used saml Tracer but for the moment it doesn't help me. I still have the AADSTS50011 error code and te tracer display this error : 
HTTP/1.1 401 Unauthorized
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: text/plain; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: https://login.microsoftonline.com, https://login.microsoftonline.com
Access-Control-Allow-Credentials: true, true
Access-Control-Allow-Methods: GET, OPTIONS, GET
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 721e4d88-0b93-4cb5-880a-b728b84b3000
x-ms-ests-server: 2.1.11722.26 - WEULR1 ProdSlices
Set-Cookie: fpc=AmKw7urELrRCs7PI9cuWAwo; expires=Wed, 07-Jul-2021 08:14:24 GMT; path=/; secure; HttpOnly; SameSite=None
x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Referrer-Policy: strict-origin-when-cross-origin
WWW-Authenticate: Negotiate
Date: Mon, 07 Jun 2021 08:14:24 GMT
Content-Length: 32

And 
Upgrade-Insecure-Requests: 1

HTTP/1.1 400 Bad Request
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Link: <https://aadcdn.msftauth.net>; rel=preconnect; crossorigin, <https://aadcdn.msftauth.net>; rel=dns-prefetch, <https://aadcdn.msauth.net>; rel=dns-prefetch
X-DNS-Prefetch-Control: on
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 3b13152e-8f43-4091-9f0e-af3997d62a00
x-ms-ests-server: 2.1.11722.26 - WEULR1 ProdSlices
Set-Cookie: buid=0.ATwAiNk02dLr802jKulp7Wj-gk2Ys5HJ609BlJVOt2jS-Co8APc.AQABAAEAAAD--DLA3VO7QrddgJg7WevrXWnOyCxc5gMQ92AY2b95nkdtZYNRRxBETXC2THnPKu2iZMucNyHu2mhiwIzKDk5gLWfnW42Vh672bLHS0deMcV6pQZCAqe8_7UHocqBXNUwgAA; expires=Wed, 07-Jul-2021 08:14:59 GMT; path=/; secure; HttpOnly; SameSite=None
fpc=AhQ9yKueEEdLrbH4ExgmqMdWkVeKAQAAAEzMT9gOAAAAVr3gdQEAAABqzE_YDgAAABMjEpICAAAAf8xP2A4AAAA; expires=Wed, 07-Jul-2021 08:14:59 GMT; path=/; secure; HttpOnly; SameSite=None
x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Referrer-Policy: strict-origin-when-cross-origin
Date: Mon, 07 Jun 2021 08:14:59 GMT
Content-Length: 17795

**Comment by derricksmith** [comment]
I added several changes since this was reported.  Can you upgrade to version 1.1.2?

If the issue persists please send the full output of SAML-tracer and each SAML request/response output also.  You can email me at derricksmith01@msn.com if you're concerned about posting online.
