### ISSUE TITLE
Question - is there a way to bypass the plugin in case of need

### ISSUE THREAD

**Issue by mklimasz5** [derricksmith/phpsaml#30]
Hi

The plugin works great (thanks!) yet some of the devices may not get the authenticated (nuances associated with Identity Provider, especially for mobile devs) and I'd need to grant them access someway. Is there a way to bypass the plugin and offer (through cleverly crafted link, for example) direct access to user/password style of authentication (existing previously in the system)?

**Comment by derricksmith** [comment]
Same issue as #23 .  I am working on a new release to address this.

**Comment by derricksmith** [comment]
Added local login capability in release 1.1.0

**Comment by mklimasz5** [comment]
Thanks for Your help - highly appreciated!!!!
I've posted my comment (some issue to use 1.1.0) on #23 before noticing it was closed. Should we continue on this thread?

**Comment by derricksmith** [comment]
Thanks for the info on the update script.  I'll review and correct.

If you're getting a blank page then it may be a php error.  What do you logs show?

Are the database values saved in requested_authn_context and requested_authn_context_comparison after you select them and save?  For the original configuration, the requested_authn_context should be set to passwordprotectedtransport and requested_authn_context_comparison should default to exact.

**Comment by derricksmith** [comment]
I was able to recreate your issue and resolve.  I've updated the 1.1.0 branch.

**Comment by mklimasz5** [comment]
Thanks Derrick!

var/log/httpd/error_log shows nothing, since the correction in the database (there were some indexing problems, but they're gone since db has been supplied with missing columns)

values in aforementioned columns are stored correctly, currently they are:
requested_authn_context = PasswordProtectedTransport
requested_authn_context_comparison = exact

/files/_log/php-errors.log is a little more informative, as it contains:

[2021-01-28 16:40:32] glpiphplog.CRITICAL:   *** Uncaught Exception OneLogin\Saml2\Error: Invalid array settings: sp_cert_not_found_and_required in /var/www/html/plugins/phpsaml/lib/php-saml/srt/Saml2/Settings.php  at line 141
  Backtrace :
  ...ins/phpsaml/lib/php-saml/src/Saml2/Auth.php:167 OneLogin\Saml2\Settings->__construct()
  plugins/phpsaml/inc/phpsaml.class.php:35           OneLogin\Saml2\Auth->__construct()
  plugins/phpsaml/inc/phpsaml.class.php:25           PluginPhpsamlPhpsaml::init()
  plugins/phpsaml/setup.php:150                      PluginPhpsamlPhpsaml->__construct()
  inc/plugin.class.php:1365                          plugin_post_init_phpsaml()
  inc/plugin.class.php:231                           Plugin::doHook()
  inc/includes.php:106                               Plugin->init()
  index.php:55                                       include()

...which seem to fail on _loadSettingsFromArray($settings)

Is there anything I should correct still? My settings are the same as before (some are new, thou, compared to version 1.0.0:
- plugin enforced = No
- Strict = No
- Debug = Yes
- SPCert = empty
- SPCertKey = empty
- IP Entity ID = set correctly, the same as before
- IP SSO URL = set correctly, the same as before
- IP Public X509 = verified, the same as before
- SAC Selected = PasswordProtectTransport
- RAC = exact

**Comment by derricksmith** [comment]
Problem was in some of the default security parameters I added to the new config settings.  I've commented out the below which will allow empty SP certs.

// Indicates whether the <samlp:AuthnRequest> messages sent by this SP
				// will be signed.              [The Metadata of the SP will offer this info]
				//'authnRequestsSigned' => true,

				// Indicates whether the <samlp:logoutRequest> messages sent by this SP
				// will be signed.
				//'logoutRequestSigned' => true,

				// Indicates whether the <samlp:logoutResponse> messages sent by this SP
				// will be signed.
				//'logoutResponseSigned' =>true,

**Comment by derricksmith** [comment]
I also corrected the install script so the tables are updated correctly when upgrading from 1.0.0 to 1.1.0.

**Comment by mklimasz5** [comment]
My pleasure to confirm - works like a charm! :) Removing the mandatory encryption on the SP side did the trick.

Thanks a lot Derrick! :) :) :) 🥇
