### ISSUE TITLE
Use plugin on Docker

### ISSUE THREAD

**Issue by VictorFaubeau** [derricksmith/phpsaml#31]
hello,

I use glpi with docker listening on port 9000.
I did put the nginx redirection from port 443 to port 9000 but when I try to connect in SSO, after Google authentication, I get the error "Not Found The requested URL was not found on this server. Apache/2.4.38 (Debian) Server at 127.0.0.1 Port 9000".
I don't understand why it goes through Apache.
So I created the redirection from port 443 to 9000 on Apache as well and the problem remains the same.

I tried to modify 127.0.0.1 on proxy_pass with the IP of my server in my nginx.conf but the error remains the same.

Could you help me?
Your plugin would be a great help for my company.

Thank you in advance.

![apache_redirection_sso](https://user-images.githubusercontent.com/72255982/102346323-f273f380-3f9e-11eb-8b05-ebfc1073fcbe.png)
![nginx_redirection_sso](https://user-images.githubusercontent.com/72255982/102346854-d45ac300-3f9f-11eb-99ad-4cfb39079948.png)
![apacheconf_redirection_sso](https://user-images.githubusercontent.com/72255982/102346932-f6ecdc00-3f9f-11eb-9b34-6ec6afbe6a89.png)

**Comment by derricksmith** [comment]
I'm not familiar enough with Docker and Nginx to help troubleshoot this.  The issue does not appear to be plugin related as GLPI will just respond to whatever webserver is hosting the pages.

As a shot in the dark, perhaps simplify your configuration by eliminating one of the webservers (either apache or nginx) and perform the HTTPS redirection within the same webserver.  Sorry I can't be more help.
