### ISSUE TITLE
GAdmin has no attribute mappings

### ISSUE THREAD

**Issue by kim3-sudo** [derricksmith/phpsaml#40]
GLPI (presumably) has fields that should be mapped to Google Directory. Examples of Google Directory attributes include first name, last name, primary email, phone number, and address. At least one and as many as needed should be mapped to an app attribute (something in GLPI that matches the data in Google Directory to complete user authentication).

Potential resolution: investigate what the GLPI app attribute should be, add to documentation

**Comment by derricksmith** [comment]
Currently, there is no field mapping.  The plugin only checks the nameID for an email match.  (Line 64 in phpsaml.class.php).  

This would be a good enhancement.  I'll consider it in a future release along with JIT provisioning.

**Comment by derricksmith** [comment]
Added field mapping for Name, Firstname, Surname, Emailaddress.
```
$password = bin2hex(random_bytes(20));
					
					$input = array(
						"name" => SELF::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'][0],
						"realname" => SELF::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'][0],
						"firstname" => SELF::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/firstname'][0],
						"_useremails" => array(SELF::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'][0]),
						"password" => $password,
						"password2" => $password,
					);
```
