### ISSUE TITLE
Name ID not in documentation

### ISSUE THREAD

**Issue by kim3-sudo** [derricksmith/phpsaml#41]
The name ID defines the naming format supported by the IdP. If my memory serves me correctly, this *should* be set to TRANSIENT, but I may be wrong. Possible options are:

- UNSPECIFIED
- EMAIL
- X509_SUBJECT
- WIN_DOMAIN_QUALIFIED
- KERBEROS
- ENTITY
- PERSISTENT
- TRANSIENT
- ENCRYPTED

The name ID that is provided by the IdP should provide either the email, first name, or last name of the user to the app (GLPI).

Possible resolution: Determine the correct naming format to be configured in the SAML settings of the IdP and add to the documentation.

**Comment by derricksmith** [comment]
This is a good suggestion.  I believe you are correct regarding the Transient option.  I'll work on getting this added to the docs.

**Comment by derricksmith** [comment]
Added option to choose NameID format in version 1.1.2.  Updated documentation.
