### ISSUE TITLE
Special installation for this plugin

### ISSUE THREAD

**Issue by christianlx** [derricksmith/phpsaml#42]
Hi Derrick,

I'd like to test your plugin to plug an azure AD to my GLPI server. The problem seems to be stupid but I don't see it in the plugin page to install and configure it. No errors in httpd or glpi logs
I 've extracted the zip to the plugin directory, chown to apache but nothing appears. Is there another method ?

I use a Centos server, php 7.3
Thanks,
Christian.

**Comment by melmoatadid** [comment]
hello @christianlx ! i have the same issue as yours with GLPI 9.5.3. well if i find a solution i will post an update.

**Comment by melmoatadid** [comment]
i think i found it, try to rename the folder you just extrated like for example "phpsaml" without special characters using only letters

**Comment by christianlx** [comment]
Finally, it was quite simple. Renaming without the "-" fix the issue. I'm now going to contact the the azure sysadmin for the configuration. Thanks.
