### ISSUE TITLE
SAML invalid Response

### ISSUE THREAD

**Issue by floriangrisolet** [derricksmith/phpsaml#45]
Hello,

I configured the plugin with azure. By using the SSO button, I get correctly the Azure login page, my user is well authorized on the azure application but I get the following error message: Signature validation failed. SAML Response rejected. 

Can you help me? 

thank you

**Comment by floriangrisolet** [comment]
Hello,

Now I get a blank page. URL: https://xxxxx/plugins/phpsaml/front/acs.php. 
No error message

Can you help me?

**Comment by floriangrisolet** [comment]
I think I have found the beginning of an answer. 
If I have a local GLPI user with an azure email address in user profile GLPI, the SSO is OK
But if the user is unknown on GLPI or if the email address does not match, the SSO is KO

**Comment by derricksmith** [comment]
The plug-in will display a GLPI user error on the front end if the user doesn't exist.  Your error is because no user was passed from SAML to the plug-in.  It passed a NULL value.

**Comment by floriangrisolet** [comment]
How is it done? 
Is it an Azure configuration error?

**Comment by AmritanshuAVerma** [comment]
I am trying to Integrate KeyCloak with SAML 2.0 on GLPI. I am getting the same issue. 
Any help will be appreciated.
P.S : Please connect with me on amritanshuverma1993@gmail.com whenever you can.

**Comment by derricksmith** [comment]
> 
> 
> I am trying to Integrate KeyCloak with SAML 2.0 on GLPI. I am getting the same issue.
> Any help will be appreciated.
> P.S : Please connect with me on [amritanshuverma1993@gmail.com](mailto:amritanshuverma1993@gmail.com) whenever you can.
> ![image](https://user-images.githubusercontent.com/40417442/112430230-ddf48380-8d63-11eb-93ee-b46a68733f09.png)

This is a different issue from the OP.  Please open a new issue.

**Comment by derricksmith** [comment]
> 
> 
> How is it done?
> Is it an Azure configuration error?

It looks like the method $auth->checkUserData() on line 64 of phpsaml.class.php is failing due to a null value being passed by the IdP which is throwing the error you posted on March 10.  I could add a try/catch block to make that fail more gracefully.  That would make the experience better.

**Comment by AmritanshuAVerma** [comment]
Thanks a lot.
I was not able to pinpoint which is failing ,the request or the response.
Please add a catch too.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AmritanshuAVerma** [comment]
Will do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derricksmith** [comment]
Can you check your IdP config for NameId?  It should be "Email Address"

**Comment by AmritanshuAVerma** [comment]
Will check and get back to you.

Thanks 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derricksmith** [comment]
Any update?

**Comment by derricksmith** [comment]
I added a configuration option to change the nameid sent to the idp in version 1.1.2.  Check this version and let me know if that resolves your issue. #55
