### ISSUE TITLE
Authentication it only works for the first type

### ISSUE THREAD

**Issue by rafaelkuhl** [derricksmith/phpsaml#46]
Hi!

First of all, id like to say thanks for this plugin! Its a great work!

I only found one problem, if I select more than 1 type of authentication it only works for the first type.

![image](https://user-images.githubusercontent.com/26922162/111881298-b68a6900-89a7-11eb-9fbf-9d0592b23581.png)

In that example I cant authenticate using Windows Hello integration.

![image](https://user-images.githubusercontent.com/26922162/111881358-0832f380-89a8-11eb-93d1-4e8355998bfd.png)

But if I remove 

![image](https://user-images.githubusercontent.com/26922162/111881405-28fb4900-89a8-11eb-8c5b-66c495d89aad.png)

The Windows Hello integration works.

**Comment by derricksmith** [comment]
I see in your first screenshot that you have "Requested Authn Comparison" set to "Exact".  Have you attempted to change that to "Minimum"? Make sure to keep the Order (Password, X509) the same.

**Comment by rafaelkuhl** [comment]
I change to:

![image](https://user-images.githubusercontent.com/26922162/112531937-1ade6b80-8da0-11eb-9d16-6c440dc01b18.png)

and try to authenticate:

![image](https://user-images.githubusercontent.com/26922162/112531899-0e5a1300-8da0-11eb-8483-d21d356bab23.png)

**Comment by derricksmith** [comment]
After further research AAD only supports 'exact' AuthnContext Comparison.  The Onelogin library allows us to send no AuthContext by settings the 'requestedAuthnContext' to false.  Currently the plugin does not allow this and will send null if requestedAuthnContext is not set in the configuration. 

To change this behavior change line 329 of phpsaml.class.php to:

'requestedAuthnContext' => (isset($config["requested_authn_context"]) && !empty($config["requested_authn_context"]) ? self::getAuthn($config["requested_authn_context"]) : false),

Then remove all Requested Authn entries in the configuration.  
![image](https://user-images.githubusercontent.com/7143479/112646741-6a0eb580-8e0d-11eb-93cc-0de7aec20dd8.png)

If this works for you, I can update the code on the next version.

**Comment by derricksmith** [comment]
Checking on this,  did that work for you?

**Comment by derricksmith** [comment]
Closing this issue due to no response.
