### ISSUE TITLE
Invalid SAML Response

### ISSUE THREAD

**Issue by AmritanshuAVerma** [derricksmith/phpsaml#47]
Getting the following error when configuring with Keycloak.
I am not able to pinpoint where is this error coming from , any help is appreciated.
I can share the configurations on a private mail if needed.

Thankyou !

![image](https://user-images.githubusercontent.com/40417442/112590671-3c376a00-8e29-11eb-8c87-f0fc71732534.png)

**Comment by derricksmith** [comment]
Sure, please send your config screenshots to derricksmith01@msn.com.

**Comment by derricksmith** [comment]
Make sure the NameID format at the IdP is "Email Address".  Sometimes it defaults to unspecified or transient.  I've seen this cause issues.

**Comment by AmritanshuAVerma** [comment]
The NameID Format is "email", and it's a dropdown , I can't add Custome Strings.
________________________________

**Comment by derricksmith** [comment]
Have you run SAML Tracer in firefox?  Can you do this and provide the output?

**Comment by AmritanshuAVerma** [comment]
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_f2ba3a5c9474f965f67042a3359bc43339662a50" Version="2.0" IssueInstant="2021-04-01T15:48:23Z" Destination="https://idp.avconference.in/auth/realms/scribeemr/protocol/saml" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://glpidemo.focusedumatics.com/plugins/phpsaml/front/acs.php"> <saml:Issuer>https://glpidemo.focusedumatics.com/</saml:Issuer> <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" AllowCreate="true"/> <samlp:RequestedAuthnContext Comparison="exact"> <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:X509</saml:AuthnContextClassRef> </samlp:RequestedAuthnContext> </samlp:AuthnRequest>


<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://glpidemo.focusedumatics.com/plugins/phpsaml/front/acs.php" ID="ID_71563b6a-1ab2-4449-b333-1a03955f7ac4" IssueInstant="2021-04-01T15:48:27.582Z" Version="2.0"><saml:Issuer>https://idp.avconference.in/auth/realms/scribeemr</saml:Issuer><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><dsig:Reference URI="#ID_71563b6a-1ab2-4449-b333-1a03955f7ac4"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><dsig:DigestValue>kSKqDrtrtMRA7IqhYX5OAZL3Ig4=</dsig:DigestValue></dsig:Reference></dsig:SignedInfo><dsig:SignatureValue>YKfgw7frveMZG4/utvm+YVvjOnSkOjOjCcE7btktYspETPoh8xy9gSuydN9I7YqN4Hp+9oJQfCGEzwzIJwOdhkhoJAuAqMu5oeY4ybHVlpd5ox345r3mV/qlviXF2bbl+P3zdx5EPI++vJ7tQchgu1jiWemvt/swvO4ZIsutiejTYKx22DkiOgkqvyYxjAmUFWmqB7XSPzd3Zpnu8desDiLcT2Edji0hYMHyfMBOYnoXVA8J7fKlFaBST7FhNvIC8orxF9jLGTOetrmKXMbUs7eTR9rbfAf2BT20EXfrn/iBIA5LDMdHAQad75VKqWw14oowg5yv6yptoTnt7PxmbA==</dsig:SignatureValue><dsig:KeyInfo><dsig:KeyName>IW84G1aK-1OMbCfmO-W4R1FYM346tur8UML5NRlhmRA</dsig:KeyName><dsig:X509Data><dsig:X509Certificate>MIICoTCCAYkCBgF3gKZ2tDANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAlzY3JpYmVlbXIwHhcNMjEwMjA4MDc1NzA5WhcNMzEwMjA4MDc1ODQ5WjAUMRIwEAYDVQQDDAlzY3JpYmVlbXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3z4piwe83QNFu8MAjKl6dK92FvcuEq21vQK2YJo2PfDHJXphO3Y2iOgK5ync65+H9sPOFKUTNHqE9nRaZXGfx7BkkoQx0yWkgO1iXL/ybuD7tSskeWt/TZ4e6KnI0Fes2j9fvoWarEa6OX1WU+mQtK71LOlGQ0CEW4OodLUUzFU7qhenRmIzyoq189peZQs8uDCdFk8JALB6IwJtKq3Qz4Ag4BqXQEztOy9xleVmpfgnUBxUqW+3zrDRTVQmTJIbWV8XxI9F8vr/pwFEMTizCARPreMPo5WTziJVKpWRxWqvrCiySp2uJpboB75KfH5ejCmjwYsMKI/cV2wtKH3vlAgMBAAEwDQYJKoZIhvcNAQELBQADggEBABCXoqEruoeF+eNTNyWIA2p3QWs9BOhgXgwlElppBW0qVqGg2L89LtJ7Ml5R7imzb+PC8MU2TM4BE6y1dyPqWr/YZHFyAu4D+h+4CtFUQJBFO2NKBlfsfRLo++MdI34sN1Gy1Fvf8MONCLD4vfVv6+TzpqQoCOEWTKraHleFSjMeS82AInIRlSxrKrJYWroB47qgIIGp1MvUzdbXQOPA1pfCvW8xd9OcofUHVVksX1yCzefV9iMA8IvkOZiIvmJHH7GNWhoHiLCwXOSJ9d3EVxs52xHbSBznMszVIsESr8wV7AbzLvhZHeeu48hzSvrM5cf0I8k0iHNuBxlkG6PKw1M=</dsig:X509Certificate></dsig:X509Data><dsig:KeyValue><dsig:RSAKeyValue><dsig:Modulus>t8+KYsHvN0DRbvDAIypenSvdhb3LhKttb0CtmCaNj3wxyV6YTt2NojoCucp3Oufh/bDzhSlEzR6hPZ0WmVxn8ewZJKEMdMlpIDtYly/8m7g+7UrJHlrf02eHuipyNBXrNo/X76FmqxGujl9VlPpkLSu9SzpRkNAhFuDqHS1FMxVO6oXp0ZiM8qKtfPaXmULPLgwnRZPCQCweiMCbSqt0M+AIOAal0BM7TsvcZXlZqX4J1AcVKlvt86w0U1UJkySG1lfF8SPRfL6/6cBRDE4swgET63jD6OVk84iVSqVkcVqr6woskqdriaW6Ae+Snx+Xowpo8GLDCiP3FdsLSh975Q==</dsig:Modulus><dsig:Exponent>AQAB</dsig:Exponent></dsig:RSAKeyValue></dsig:KeyValue></dsig:KeyInfo></dsig:Signature><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy"/></samlp:StatusCode></samlp:Status></samlp:Response>
________________________________

**Comment by derricksmith** [comment]
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy"/></samlp:StatusCode>

Looking at the request, it appears GLPI is sending "unspecified".  I misspoke earlier, after checking the code in phpsaml.class.php on line 235, GLPI is configured to send "unspecified".  Are you able to change to unspecified at the IdP?

**Comment by AmritanshuAVerma** [comment]
No I don't think so.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gtinging** [comment]
hi.

I also use keycloak to configure SSO.

If you succeed, please provide some information about the main parameters.

thank you!

**Comment by AmritanshuAVerma** [comment]
Any Luck ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by derricksmith** [comment]
I created a new branch 1.1.2 and added a configuration field for NameID.  The cooresponding PHPSAML array item for NameIDFormat now looks at this config option.  If is not entered it will use unspecified.

'''
'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:'.(isset($config['saml_sp_nameid_format']) ? $config['saml_sp_nameid_format'] : 'unspecified'),

'''

Can you test and let me know if that works for you?

**Comment by AmritanshuAVerma** [comment]
will test it and get back to you , thanks for doing this man

**Comment by AmritanshuAVerma** [comment]
We tested the new version and made changes on our end as well but still getting the issue.


<?xml version="1.0" encoding="UTF-8"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://glpidemo.focusedumatics.com/plugins/phpsaml/front/acs.php" ID="ID_040be45c-a51a-4d9f-9d06-58512c206c16" InResponseTo="ONELOGIN_f51e8d66cced952e0715cb8d3b30f60877fcaba4" IssueInstant="2021-07-16T05:54:08.637Z" Version="2.0">
   <saml:Issuer>https://idp.avconference.in/auth/realms/scribeemr</saml:Issuer>
   <dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
      <dsig:SignedInfo>
         <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <dsig:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
         <dsig:Reference URI="#ID_040be45c-a51a-4d9f-9d06-58512c206c16">
            <dsig:Transforms>
               <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </dsig:Transforms>
            <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
            <dsig:DigestValue>vR/CG07Qp9yKgAzzp/RoaMQIL4k=</dsig:DigestValue>
         </dsig:Reference>
      </dsig:SignedInfo>
      <dsig:SignatureValue>mcG7uQZhTcV2hWrd6Lk4YDprg2fxGacgwbUh0YIGkndnV7N7S1il82noySwf7nCP2DdqAVUyy3ttShJVhQOD3WFQjmdmRB70g8k2OdNVe+eGcsnd/sqUxLALF5hGXIczqrGZRzebctKr8LuNZOSCndTOBJeiZ2xbk0eNSmSxAdpQ8EB+dzbRtdcmIoxaxg7AQ/7M44kVDT9qV/dxl+EkEqjE7Ubi1QrnpTIsGL9HrZ2ldrUqtkrPDnhYw4LhxFJC1OXMC50zUUt7FgnnNoJlio4aAKgFJqalYr65cApq7hntpG6G2cR/kvjB77apm6R8inzfiOIkd2WZBAqYd5s6Vw==</dsig:SignatureValue>
      <dsig:KeyInfo>
         <dsig:KeyName>IW84G1aK-1OMbCfmO-W4R1FYM346tur8UML5NRlhmRA</dsig:KeyName>
         <dsig:X509Data>
            <dsig:X509Certificate>MIICoTCCAYkCBgF3gKZ2tDANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAlzY3JpYmVlbXIwHhcNMjEwMjA4MDc1NzA5WhcNMzEwMjA4MDc1ODQ5WjAUMRIwEAYDVQQDDAlzY3JpYmVlbXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3z4piwe83QNFu8MAjKl6dK92FvcuEq21vQK2YJo2PfDHJXphO3Y2iOgK5ync65+H9sPOFKUTNHqE9nRaZXGfx7BkkoQx0yWkgO1iXL/ybuD7tSskeWt/TZ4e6KnI0Fes2j9fvoWarEa6OX1WU+mQtK71LOlGQ0CEW4OodLUUzFU7qhenRmIzyoq189peZQs8uDCdFk8JALB6IwJtKq3Qz4Ag4BqXQEztOy9xleVmpfgnUBxUqW+3zrDRTVQmTJIbWV8XxI9F8vr/pwFEMTizCARPreMPo5WTziJVKpWRxWqvrCiySp2uJpboB75KfH5ejCmjwYsMKI/cV2wtKH3vlAgMBAAEwDQYJKoZIhvcNAQELBQADggEBABCXoqEruoeF+eNTNyWIA2p3QWs9BOhgXgwlElppBW0qVqGg2L89LtJ7Ml5R7imzb+PC8MU2TM4BE6y1dyPqWr/YZHFyAu4D+h+4CtFUQJBFO2NKBlfsfRLo++MdI34sN1Gy1Fvf8MONCLD4vfVv6+TzpqQoCOEWTKraHleFSjMeS82AInIRlSxrKrJYWroB47qgIIGp1MvUzdbXQOPA1pfCvW8xd9OcofUHVVksX1yCzefV9iMA8IvkOZiIvmJHH7GNWhoHiLCwXOSJ9d3EVxs52xHbSBznMszVIsESr8wV7AbzLvhZHeeu48hzSvrM5cf0I8k0iHNuBxlkG6PKw1M=</dsig:X509Certificate>
         </dsig:X509Data>
         <dsig:KeyValue>
            <dsig:RSAKeyValue>
               <dsig:Modulus>t8+KYsHvN0DRbvDAIypenSvdhb3LhKttb0CtmCaNj3wxyV6YTt2NojoCucp3Oufh/bDzhSlEzR6hPZ0WmVxn8ewZJKEMdMlpIDtYly/8m7g+7UrJHlrf02eHuipyNBXrNo/X76FmqxGujl9VlPpkLSu9SzpRkNAhFuDqHS1FMxVO6oXp0ZiM8qKtfPaXmULPLgwnRZPCQCweiMCbSqt0M+AIOAal0BM7TsvcZXlZqX4J1AcVKlvt86w0U1UJkySG1lfF8SPRfL6/6cBRDE4swgET63jD6OVk84iVSqVkcVqr6woskqdriaW6Ae+Snx+Xowpo8GLDCiP3FdsLSh975Q==</dsig:Modulus>
               <dsig:Exponent>AQAB</dsig:Exponent>
            </dsig:RSAKeyValue>
         </dsig:KeyValue>
      </dsig:KeyInfo>
   </dsig:Signature>
   <samlp:Status>
      <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </samlp:Status>
   <saml:Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="ID_8f04bd5b-f2bc-4def-a811-2bed0dc53131" IssueInstant="2021-07-16T05:54:08.637Z" Version="2.0">
      <saml:Issuer>https://idp.avconference.in/auth/realms/scribeemr</saml:Issuer>
      <saml:Subject>
         <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">glpiadmin</saml:NameID>
         <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml:SubjectConfirmationData InResponseTo="ONELOGIN_f51e8d66cced952e0715cb8d3b30f60877fcaba4" NotOnOrAfter="2021-07-16T05:59:06.637Z" Recipient="https://glpidemo.focusedumatics.com/plugins/phpsaml/front/acs.php" />
         </saml:SubjectConfirmation>
      </saml:Subject>
      <saml:Conditions NotBefore="2021-07-16T05:54:06.637Z" NotOnOrAfter="2021-07-16T05:55:06.637Z">
         <saml:AudienceRestriction>
            <saml:Audience>https://glpidemo.focusedumatics.com/</saml:Audience>
         </saml:AudienceRestriction>
      </saml:Conditions>
      <saml:AuthnStatement AuthnInstant="2021-07-16T05:54:08.637Z" SessionIndex="9be22b4c-716b-48ca-947a-6cc3ef4bf241::3dbaf278-94fe-4df0-af5d-a012375401d5" SessionNotOnOrAfter="2021-07-16T15:54:08.637Z">
         <saml:AuthnContext>
            <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
         </saml:AuthnContext>
      </saml:AuthnStatement>
      <saml:AttributeStatement>
         <saml:Attribute FriendlyName="username" Name="username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
            <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">glpiadmin</saml:AttributeValue>
         </saml:Attribute>
         <saml:Attribute FriendlyName="givenName" Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
            <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">admin</saml:AttributeValue>
         </saml:Attribute>
         <saml:Attribute FriendlyName="email" Name="urn:oid:1.2.840.113549.1.9.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
            <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">glpiadmin@gmail.com</saml:AttributeValue>
         </saml:Attribute>
         <saml:Attribute FriendlyName="surname" Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
            <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">glpi</saml:AttributeValue>
         </saml:Attribute>
      </saml:AttributeStatement>
   </saml:Assertion>
</samlp:Response>

**Comment by AmritanshuAVerma** [comment]
StackTrace from Firefox plugin

GET https://idp.avconference.in/auth/realms/scribeemr/protocol/saml?SAMLRequest=jVPbrtowEHznK1DeiZNQLrUgEoVekCggoFXVl8o4G7AUX%2Bq1T8%2F5%2BzoJFFq1qH6c3RnvjNcTZLIydObdWe3guwd0nW44z7JSSJviNPJWUc1QIFVMAlLH6X72cUWzOKHGaqe5rqI%2FaI9ZDBGsE1q1tOViGm3Wb1eb98v1txErsmQ0HqfA2KA%2FHh%2F7POsXCWNFMu6XacqzMhsMj8OW%2BhksBp1pFGSjTquG6GGp0DHlAp5kaS8Z9dLhIRnSVxlNsq8tdRHMCsVcQz87Z5ASIgoTsyeuVQkWFIdYKMJCOsQCqyQS5FYcAaQlV%2Bekttsqbi%2FQG6EKoU6PMzi2TUg%2FHA7b3nazP7Qis2s2c63QS7B7sE%2BCw6fd6jbmqTKiAKnjUnOPUHgZfHCMuZbEVP4kFBJzNvVopLRaOcJCNSBR3lwyqSu0Scrm%2FyM6IfeMm4ah6%2BBsudjqSvCXBq%2FPO20D%2Bd8BpHHaIKLolU0r9QoNcFEKKKJfMrOq0j%2FmIXoH08hZD1GX%2FHb5ZWehaDY4JObg2XXnWhpmBdYPK4US0suL75v3e8K8Cgu5gzJ%2FuLOc8rovwF8GyetLIH%2BVaSckD0bMO9fy%2FdfLfwI%3D&RelayState=https%3A%2F%2Fglpidemo.focusedumatics.com%2Findex.php%3FSSO%3D1 HTTP/1.1
Host: idp.avconference.in
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://glpidemo.focusedumatics.com/
Connection: keep-alive
Cookie: AUTH_SESSION_ID=252077d3-1f3e-4270-9a8d-fb1ad4a414cb.meeting; AUTH_SESSION_ID_LEGACY=252077d3-1f3e-4270-9a8d-fb1ad4a414cb.meeting; KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTY2MDBlMi1lOTI0LTRhYjctOWUwNy1jZWE4OTAwYmE1OTgifQ.eyJleHAiOjE2MjY0NTM2MTMsImlhdCI6MTYyNjQxNzYxMywianRpIjoiY2U4ZTVmOTctNTAxZC00MmIyLTk4ZmItYjcwOTViYmFjNTcwIiwiaXNzIjoiaHR0cHM6Ly9pZHAuYXZjb25mZXJlbmNlLmluL2F1dGgvcmVhbG1zL3NjcmliZWVtciIsInN1YiI6IjJmYzQ5OTkyLTE1ZWUtNDczYi1iODY2LWIxYmY4OTAxMDAxYSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiMjUyMDc3ZDMtMWYzZS00MjcwLTlhOGQtZmIxYWQ0YTQxNGNiIiwic3RhdGVfY2hlY2tlciI6IldYZEtQSnhaNU1YRHc5a0VQMjltcWVGVUhEWWsxUnJfUE5aREFONVFaSmsifQ.9Ao0GduFKrP1pLvWNS-WruVGxeiULorFHGnHp1O-XsU; KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTY2MDBlMi1lOTI0LTRhYjctOWUwNy1jZWE4OTAwYmE1OTgifQ.eyJleHAiOjE2MjY0NTM2MTMsImlhdCI6MTYyNjQxNzYxMywianRpIjoiY2U4ZTVmOTctNTAxZC00MmIyLTk4ZmItYjcwOTViYmFjNTcwIiwiaXNzIjoiaHR0cHM6Ly9pZHAuYXZjb25mZXJlbmNlLmluL2F1dGgvcmVhbG1zL3NjcmliZWVtciIsInN1YiI6IjJmYzQ5OTkyLTE1ZWUtNDczYi1iODY2LWIxYmY4OTAxMDAxYSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiMjUyMDc3ZDMtMWYzZS00MjcwLTlhOGQtZmIxYWQ0YTQxNGNiIiwic3RhdGVfY2hlY2tlciI6IldYZEtQSnhaNU1YRHc5a0VQMjltcWVGVUhEWWsxUnJfUE5aREFONVFaSmsifQ.9Ao0GduFKrP1pLvWNS-WruVGxeiULorFHGnHp1O-XsU; KEYCLOAK_SESSION=scribeemr/2fc49992-15ee-473b-b866-b1bf8901001a/252077d3-1f3e-4270-9a8d-fb1ad4a414cb; KEYCLOAK_SESSION_LEGACY=scribeemr/2fc49992-15ee-473b-b866-b1bf8901001a/252077d3-1f3e-4270-9a8d-fb1ad4a414cb
Upgrade-Insecure-Requests: 1

HTTP/2.0 200 OK
server: nginx/1.18.0 (Ubuntu)
date: Fri, 16 Jul 2021 06:42:04 GMT
content-type: text/html;charset=utf-8
vary: Accept-Encoding
cache-control: no-store, must-revalidate, max-age=0
set-cookie: KC_RESTART=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTY2MDBlMi1lOTI0LTRhYjctOWUwNy1jZWE4OTAwYmE1OTgifQ.eyJjaWQiOiJodHRwczovL2dscGlkZW1vLmZvY3VzZWR1bWF0aWNzLmNvbS8iLCJwdHkiOiJzYW1sIiwicnVyaSI6Imh0dHBzOi8vZ2xwaWRlbW8uZm9jdXNlZHVtYXRpY3MuY29tL3BsdWdpbnMvcGhwc2FtbC9mcm9udC9hY3MucGhwIiwiYWN0IjoiQVVUSEVOVElDQVRFIiwibm90ZXMiOnsiUmVsYXlTdGF0ZSI6Imh0dHBzOi8vZ2xwaWRlbW8uZm9jdXNlZHVtYXRpY3MuY29tL2luZGV4LnBocD9TU089MSIsIlNBTUxfUkVRVUVTVF9JRCI6Ik9ORUxPR0lOXzdhZDIwNzg4MWVhYTUzODhiM2MyM2QwYWFkMDgzZjExYzJmMjU2YjYiLCJzYW1sX2JpbmRpbmciOiJwb3N0In19.zGdHGFLiqdRs_oZOkb-NBjnbLiW3yaBC5LMSZHqEEAY; Version=1; Path=/auth/realms/scribeemr/; SameSite=none; HttpOnly
KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/scribeemr/; SameSite=none; HttpOnly
KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/scribeemr/; SameSite=none; HttpOnly
KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTY2MDBlMi1lOTI0LTRhYjctOWUwNy1jZWE4OTAwYmE1OTgifQ.eyJleHAiOjE2MjY0NTM3MjQsImlhdCI6MTYyNjQxNzcyNCwianRpIjoiOWZiNjU1NGMtNjNmYy00NmVmLWExZTEtYjA2NDNkMGIxNDhjIiwiaXNzIjoiaHR0cHM6Ly9pZHAuYXZjb25mZXJlbmNlLmluL2F1dGgvcmVhbG1zL3NjcmliZWVtciIsInN1YiI6IjJmYzQ5OTkyLTE1ZWUtNDczYi1iODY2LWIxYmY4OTAxMDAxYSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiMjUyMDc3ZDMtMWYzZS00MjcwLTlhOGQtZmIxYWQ0YTQxNGNiIiwic3RhdGVfY2hlY2tlciI6IldYZEtQSnhaNU1YRHc5a0VQMjltcWVGVUhEWWsxUnJfUE5aREFONVFaSmsifQ.7oDy_ohyBiZdBsxGf1GV881FSN4gdWT71yVZo8h_duo; Version=1; Path=/auth/realms/scribeemr/; SameSite=none; SameSite=None; Secure; HttpOnly
KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmYTY2MDBlMi1lOTI0LTRhYjctOWUwNy1jZWE4OTAwYmE1OTgifQ.eyJleHAiOjE2MjY0NTM3MjQsImlhdCI6MTYyNjQxNzcyNCwianRpIjoiOWZiNjU1NGMtNjNmYy00NmVmLWExZTEtYjA2NDNkMGIxNDhjIiwiaXNzIjoiaHR0cHM6Ly9pZHAuYXZjb25mZXJlbmNlLmluL2F1dGgvcmVhbG1zL3NjcmliZWVtciIsInN1YiI6IjJmYzQ5OTkyLTE1ZWUtNDczYi1iODY2LWIxYmY4OTAxMDAxYSIsInR5cCI6IlNlcmlhbGl6ZWQtSUQiLCJzZXNzaW9uX3N0YXRlIjoiMjUyMDc3ZDMtMWYzZS00MjcwLTlhOGQtZmIxYWQ0YTQxNGNiIiwic3RhdGVfY2hlY2tlciI6IldYZEtQSnhaNU1YRHc5a0VQMjltcWVGVUhEWWsxUnJfUE5aREFONVFaSmsifQ.7oDy_ohyBiZdBsxGf1GV881FSN4gdWT71yVZo8h_duo; Version=1; Path=/auth/realms/scribeemr/; SameSite=none; HttpOnly
KEYCLOAK_SESSION=scribeemr/2fc49992-15ee-473b-b866-b1bf8901001a/252077d3-1f3e-4270-9a8d-fb1ad4a414cb; Version=1; Expires=Fri, 16-Jul-2021 16:42:04 GMT; Max-Age=36000; Path=/auth/realms/scribeemr/; SameSite=none; SameSite=None; Secure
KEYCLOAK_SESSION_LEGACY=scribeemr/2fc49992-15ee-473b-b866-b1bf8901001a/252077d3-1f3e-4270-9a8d-fb1ad4a414cb; Version=1; Expires=Fri, 16-Jul-2021 16:42:04 GMT; Max-Age=36000; Path=/auth/realms/scribeemr/; SameSite=none
KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/scribeemr/; SameSite=none; HttpOnly
p3p: CP="This is not a P3P policy!"
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
referrer-policy: no-referrer
content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
x-robots-tag: none
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
content-language: en
access-control-allow-origin: *
content-encoding: gzip
X-Firefox-Spdy: h2

**Comment by derricksmith** [comment]
This does not appear to be the same issue?  I don't see the below error you posted on Apr 1.  Are you receiving an error?  Can you provide it?  It would also be helpful to see the full Firefox SAML Tracer output.

<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy"/></samlp:StatusCode>

**Comment by derricksmith** [comment]
See below for sample SAML Tracer output.  

![image](https://user-images.githubusercontent.com/7143479/125968347-50ac92d4-b627-4131-9130-b49d0ec89936.png)

Click on each SAML entry and then the SAML tab to show the output.

![image](https://user-images.githubusercontent.com/7143479/125968522-b46fa6f2-3983-45bd-afde-6e63dab21337.png)

![image](https://user-images.githubusercontent.com/7143479/125968718-718b79e4-5283-4b6f-bb85-6a282da078db.png)

**Comment by adrianofante** [comment]
@AmritanshuAVerma 
Were you able to configure the integration with Keycloak?
Can you send some prints of the settings in Keycloak and also the Plugin Glpi?
