### ISSUE TITLE
Invalid array settings

### ISSUE THREAD

**Issue by masaenzg** [derricksmith/phpsaml#48]
I fill the form fields en pulgin configuration but when I try to login receive the message in the image bellow.
<img width="911" alt="Screen Shot 2021-03-26 at 10 49 32 AM" src="https://user-images.githubusercontent.com/6843196/112658340-50776900-8e21-11eb-8199-844702a2c11f.png">

What I'm doing wrong?

**Comment by derricksmith** [comment]
Are you sure the form fields saved?

**Comment by masaenzg** [comment]
Yes,  when I click in the tool icon in the image below, fill the fields and press the update button
<img width="105" alt="Screen Shot 2021-03-26 at 12 12 07 PM" src="https://user-images.githubusercontent.com/6843196/112668650-c2a17b00-8e2c-11eb-8c8b-4f9eccd02c9a.png">

<img width="979" alt="Screen Shot 2021-03-26 at 12 11 53 PM" src="https://user-images.githubusercontent.com/6843196/112668671-c8975c00-8e2c-11eb-924b-cc31fce445e8.png">

**Comment by derricksmith** [comment]
I don't see any of the other fields in your screenshot?  Entity ID, Certificates?  You can obfuscate them as necessary.

**Comment by masaenzg** [comment]
<img width="1000" alt="Screen Shot 2021-03-26 at 2 27 06 PM" src="https://user-images.githubusercontent.com/6843196/112683566-bffc5100-8e3f-11eb-9d26-5838858b0a7b.png">

<img width="1092" alt="Screen Shot 2021-03-26 at 2 27 18 PM" src="https://user-images.githubusercontent.com/6843196/112683549-bb379d00-8e3f-11eb-88ec-981fd234da55.png">

**Comment by derricksmith** [comment]
Looks like you are missing the logout service URL.  I believe the Google address is "https://accounts.google.com/logout"

**Comment by masaenzg** [comment]
I put that link but the values are not saved in DB all fields are mandatory?

**Comment by derricksmith** [comment]
Do you see any errors in the GLPI php errors?

**Comment by derricksmith** [comment]
Checking on this, were you able to see if there are any php errors in the GLPI logs?

**Comment by derricksmith** [comment]
Also which version of the plugin are you using?

**Comment by derricksmith** [comment]
Closing this issue due to no response.
