### ISSUE TITLE
Clicking on specfic link -> login with saml -> auth succesffuly -> generic GLPI page opens instead of specific link

### ISSUE THREAD

**Issue by AldarisPale** [derricksmith/phpsaml#51]
Hi!

First of all, many thanks for awesome plugin.
We are using ver 1.0.0 of it.

Lets say I have link https://my.glpi.org/front/ticket.form.php?id=980 and I'm not logged in to GLPI. When I click on this link, I get transferred to SAML login. I log in am transferred back to GLPI, logged in successfully. However, I'm not directed to https://my.glpi.org/front/ticket.form.php?id=980 but to https://my.glpi.org/front/ticket.form.php instead.

We are using Google Workspace as SAML provider.

Now, I'm not sure if this is a plugin bug, GLPI bug or Google Workspace bug.

We are using GLPI 9.5.5.

**Comment by AldarisPale** [comment]
I took a closer look
1. Request comes in: GET /**index.php?redirect=ticket_38**
2. GLPI replies with: Location: htt_ps://accounts.google.com/o/saml2/idp.................&RelayState=glpi_url/**index.php**
3. SAML magic
4. GET /acs.php which now redirects us to https://glpi_url/**front/central.php?redirect=glpi_url/index.php**

So I think either RelayState passed to Google is wrong OR it's correct, but session state gets mangled somehow so that when user finally gets back, GLPI thinks that the user should see general page instead of the page user wanted to visit in the first place.

I checked phperrors.log to - looked clean.

**Comment by pablitobin** [comment]
same issue using Azure AD

**Comment by pablitobin** [comment]
any news?

**Comment by derricksmith** [comment]
I can replicate on my side.  It looks like the redirect $_GET parameter is not being passed to ssoRequest in setup.php.  I'm working on a fix.  Will publish soon.

**Comment by FlorianLbm** [comment]
Hello,

the fix works when using the button "login with SSO" but it does not work when SSO is enforced.

Regards.

**Comment by derricksmith** [comment]
> 
> 
> Derrick, I upgrade to 1.1.1 but it still does not work. And something weird, in Plugin tab, I cant see the new version number.
> ![image](https://user-images.githubusercontent.com/40396227/121027555-ac893280-c76c-11eb-8fa2-3d764a0d4bed.png)

Fixed in release version 1.1.1

**Comment by derricksmith** [comment]
> 
> 
> Hello,
> 
> the fix works when using the button "login with SSO" but it does not work when SSO is enforced.
> 
> Regards.

Can you elaborate?  What happens differently when SSO is enforced?  What is the url endpoint you are trying to redirect to?

I have tested both scenarios (SSO enforced and not enforced) with the {site}/?redirect=ticket_1 url and both redirect the visitor to the ticket.

**Comment by pablitobin** [comment]
Did you try to open that link but using incognito mode (no logged)? I mean, I have the same issue, if I never login to the platform, and I open that link, It asked me to login (Azure AD). I login, and it redirects  me to the main site, no to the original site that I open (=ticket_1). If I open the link again, it works because as I already logged it does not redirect me to login page. Make sense?

**Comment by derricksmith** [comment]
Yes, I open in private window, I'm redirected to my IdP and then redirected back to the {site}/?redirect=ticket_1 url.

**Comment by pablitobin** [comment]
it does not work for me.. if it try to access: https://xxxxxxxx/front/ticket.form.php?id=zzzzzzzz, after I login, the return address it: https://xxxxxxxx/front/central.php?redirect=https%3A%2F%2Fxxxxxxxx%2Ffront%2Fticket.form.php
![image](https://user-images.githubusercontent.com/40396227/123328372-20fbf980-d501-11eb-9d2c-0157746a5fb9.png)

**Comment by derricksmith** [comment]
ah that is the difference.  I based the code changes on the workflow outlined by @AldarisPale 

```
    Request comes in: GET /index.php**?redirect=ticket_38**
    GLPI replies with: Location: htt_ps://accounts.google.com/o/saml2/idp.................&RelayState=glpi_url/index.php
    SAML magic
    GET /acs.php which now redirects us to https://glpi_url/front/central.php?redirect=glpi_url/index.php
```
I didn't anticipate the entire url being passed as a parameter.

**Comment by FlorianLbm** [comment]
That's right, when my coworkers send me a ticket, they copy the URL https://glpi/front/ticket.form.php?id=2009280030 
When SSO is enforced, it does not work.

I made a quick fix who seems to work. The idea is to let Glpi do his things for all other page (ie go to login page and set redirect var) , but to enforce SSO only for the https://glpi/index.php page



 in setup.php : ligne 148
	//Added 1.1.0 - SSO enforcement and signin with SSO button on login page
	 - if ((isset($_GET['SSO']) && $_GET['SSO'] == 1) || (isset($config['enforced']) && $config['enforced'] == 1)){
	 + if ((isset($_GET['SSO']) && $_GET['SSO'] == 1) || (isset($config['enforced']) && $config['enforced'] == 1 && strpos($_SERVER['REQUEST_URI'], 'index.php'))){

**Comment by derricksmith** [comment]
That's an interesting approach.  Let me test it out.

**Comment by derricksmith** [comment]
I think your solution works but could cause issues with any IdP timeout settings since requests will no longer pass through to the IdP after the first login.  But I think we can just pass the REQUEST_URI to the ssoRequest in setup.php if there is no $_GET['redirect'].

line 193 on Setup.php
```
$returnTo = (isset($_GET['redirect']) ? $_GET['redirect'] : (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]");
```

**Comment by FlorianLbm** [comment]
Yes, I've made some tests, and your solution works fine.
I have no knowledge the internals of glpi, but your fix seems to be more in line with the logic use elsewhere.


And I'm sorry for my bad English, it's not my native language.

Regards,

**Comment by pablitobin** [comment]
Should be update it manually or you will deploy a new release?

**Comment by pablitobin** [comment]
I updated it and it works. Thanks!
