### ISSUE TITLE
Plugin not saving the configuration

### ISSUE THREAD

**Issue by fellipedemoraes** [derricksmith/phpsaml#52]
After config the plugin and back to conf

![image](https://user-images.githubusercontent.com/16623373/118556104-d8029980-b739-11eb-8fd3-279e60a8ced7.png)

Test from Azure Application SAML:
```
Message error: Invalid array settings: idp_entityId_not_found, idp_sso_not_found, idp_cert_or_fingerprint_not_found_and_required
Take login again
```

Thanks!

**Comment by derricksmith** [comment]
Which version?

**Comment by fellipedemoraes** [comment]
GLPI 9.5.5

**Comment by matheussinnis** [comment]
Any news regarding this issue?

**Comment by fellipedemoraes** [comment]
> Any news regarding this issue?

In tests, we let you know soon, ty!

**Comment by matheussinnis** [comment]
Thank you! Obrigado!!!

**Comment by derricksmith** [comment]
Which version of the plugin?

**Comment by matheussinnis** [comment]
> Which version of the plugin?

My GLPI is version 9.4.

The 1.0 plugin works but it points to the wrong url and I can't use GLPI.

Plugin 1.1 does not allow me to save the settings.

**Comment by matheussinnis** [comment]
Plugin 1.0 authenticates to SAML, but then sends to the URL: http://SERVER/glpi/plugins/phpsaml/front/acs.php

**Comment by derricksmith** [comment]
Sorry you are having this issue with V1.1.  I don't experience the same in my test environment so we'll need to troubleshoot.  Can you provide screenshots of your full configuration (obfuscate your IDP config and certificates)? Do you see anything in the GLPI php logs?

**Comment by derricksmith** [comment]
I added release 1.1.1 to fix a few items.  Can you try that version?

**Comment by matheussinnis** [comment]
> I added release 1.1.1 to fix a few items. Can you try that version?

I'll try.

Sorry for the delay, I had other tasks.

As soon as I have some time I'll pass you the logs.

**Comment by matheussinnis** [comment]
> I added release 1.1.1 to fix a few items. Can you try that version?

The newer version plugins (1.1.1 and 1.1.2) don't change the screen data - but I managed to do this directly in the MysQL database, via the glpi_plugin_phpsaml_configs table.

When trying to authenticate by X509, it shows the error of figure 1. 
When changing in the bank to 'Password', it shows the error of figure number 2.

Figure 1: https://ibb.co/hg18mLb
Figure 2: https://ibb.co/JnDvMM4

**Comment by derricksmith** [comment]
Thanks for the screenshots.  For figure 2, what is the GLPI config and IdP config for NameID?

With X509 in the 'requested_authn_context' field, what is the SAML tracer output?

**Comment by matheussinnis** [comment]
> Thanks for the screenshots. For figure 2, what is the GLPI config and IdP config for NameID?
> 
> With X509 in the 'requested_authn_context' field, what is the SAML tracer output?

Version 1.1.2
EmailAdress, X509

Figure 3: https://ibb.co/HCxqcgW

**Comment by matheussinnis** [comment]
> Thanks for the screenshots. For figure 2, what is the GLPI config and IdP config for NameID?
> 
> With X509 in the 'requested_authn_context' field, what is the SAML tracer output?

Want to chat on whatsapp?

**Comment by matheussinnis** [comment]
Give me your email that I send.

> Thanks for the screenshots. For figure 2, what is the GLPI config and IdP config for NameID?
> 
> With X509 in the 'requested_authn_context' field, what is the SAML tracer output?

Want to chat on whatsapp?
Give me your email that I send.

**Comment by derricksmith** [comment]
I don't use Whatsapp but you can reach me at derricksmith01@msn.com

**Comment by derricksmith** [comment]
@fellipedemoraes, any update on the original issue?  I'll leave open for a few days and then close this issue.

@matheussinnis, please open a new issue if this is still a problem.

**Comment by fellipedemoraes** [comment]
@derricksmith , thank you, we use https://github.com/edgardmessias/glpi-singlesignon

**Comment by seckka212** [comment]
Hi 
I ahve the same issue.plugin can't save configuration.I have glpi 9.5.0 and phh saml 1.2.0
