### ISSUE TITLE
Working with caldav

### ISSUE THREAD

**Issue by Riesuu** [derricksmith/phpsaml#56]
Hello,
I want to synchronize our Outlook calendars with GLPI 9.5.5. Our GLPI is on a debian 10, the SSO is activated (with your phpsaml plugin) and the application is synchronized with the azure AD.A wildcard certificate is installed on our domain glpi.xxx.fr

CALDAV for outlook does not work with the PHPSAML plugin enabled. The error I get is: 404 not found. Un
Which log would you like to have?

thank you

**Comment by derricksmith** [comment]
Is caldav a GLPI plugin?  I checked the GLPI Plugins registry and couldn't find one by that name.

Best place to start for logs is the glpi php logs 

{GLPI Web directory}/files/_log/php-errors.log

**Comment by Riesuu** [comment]
No it is an outlook plugin that allows me to synchronize my outlook calendar with the GLPI calendar via the CALDAV link
https://caldavsynchronizer.org/
![image](https://user-images.githubusercontent.com/17006344/123979993-7a609e80-d9c1-11eb-8c57-e386b3f243ac.png)
[php-errors.log](https://github.com/derricksmith/phpsaml/files/6741732/php-errors.log)

**Comment by derricksmith** [comment]
What version of phpsaml are you running?  Also, I'm not seeing a 404 error in the php logs.  Can you describe how CalDav is accessing GLPI?  Is there an specific endpoint it tries to reach?

**Comment by Riesuu** [comment]
PHPSAML 1.1.1.

URLDAV:  I have to enter the ip in http and not in https. It doesn't work with the dns name
User/pwd: I don't know why, but by deactivating phpsaml and giving a local account to glpi, it works
![image](https://user-images.githubusercontent.com/17006344/123982318-353d6c00-d9c3-11eb-84fc-4b5c405550b6.png)

![image](https://user-images.githubusercontent.com/17006344/123982564-6d44af00-d9c3-11eb-9a1f-eddafa85dd56.png)

Now phpsaml off:

![image](https://user-images.githubusercontent.com/17006344/123982788-9c5b2080-d9c3-11eb-9029-03b696a0f180.png)



working

**Comment by Riesuu** [comment]
log of caldav:

`CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '404' ('Not Found'). Message:

   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.WebDavDataAccess.<IsResourceType>d__6.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__29.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.Implementation.CalDavRepository`1.<GetAllVersions>d__9.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GenSync.EntityRepositories.VersionAwareToStateAwareEntityRepositoryAdapter`4.<GetFullRepositoryState>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GenSync.Synchronization.Synchronizer`11.<Synchronize>d__27.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<Synchronize>d__3.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunAndRescheduleNoThrow>d__22.MoveNext()`

**Comment by derricksmith** [comment]
Okay, I see the problem.  Look between the lines 152 and 174 in setup.php.  There are if statements that allow certain pages to bypass SSO.  You'll need to add an if statement for the url in your configuration.  It is not an elegant solution but there is currently no way to dynamically add urls to bypass SSO.  

Another solution that may work for you is to disable the Enforce SSO option in PHPSAML.

**Comment by Riesuu** [comment]
No problem, it reminds me of the phpbb forums ahah.

How do I fill in the url?
"../../caldav.php" 
or
https://myglpi.fr/caldav.php/calendars/users/my.user/calendar

or
../../caldav.php/calendars/users/my.user/calendar

**Comment by Riesuu** [comment]
It work !just need to write caldav.php.
Now i have another bug, but its about caldav.

Many thanks and good work.
