### ISSUE TITLE
Session does not start with credentials

### ISSUE THREAD

**Issue by riccp** [derricksmith/phpsaml#57]
Hello, I've opened the #44 issue. After that I saw the update of being able to choose the nameid format (great).

Meanwhile I've talked to the team that provide the saml/oath2 to me. It turns out they could send me the email address as the nameid format.

After some testing, I couldn't manage to login at all. The system shows me the "The action you have requested is not allowed." message.

This is a session problem. If I login using a passwordm then everything goes fine.

Apparently the sso is working because I don't see any error such as "user unknown". The only message I get is the above one.

I've cloned the project to get the latest version and setting the nameid format with no success.

The user is already created and the username is the email address.

What should I do to debug this?

**Comment by derricksmith** [comment]
Install the SAML tracer extension in firefox and send the output.  I need to see the request and the response.  See below, the example.  Also send a screenshot of the error.

See below for sample SAML Tracer output.  

![image](https://user-images.githubusercontent.com/7143479/125968821-7fdb05ea-742f-4c44-8122-5cae5e7ddf1a.png)

Click on each SAML entry and then the SAML tab to show the output.

![image](https://user-images.githubusercontent.com/7143479/125968522-b46fa6f2-3983-45bd-afde-6e63dab21337.png)

![image](https://user-images.githubusercontent.com/7143479/125968718-718b79e4-5283-4b6f-bb85-6a282da078db.png)

**Comment by riccp** [comment]
Hello Derrick, sorry for the delay.

The SAML output:

![image](https://user-images.githubusercontent.com/33662936/127057036-a0df0435-17d9-4658-a77f-e1a98e0eb2b6.png)

and

![image](https://user-images.githubusercontent.com/33662936/127057104-1d1cd21f-2f7e-42ce-9e55-049b76bdcf14.png)

The error message:

![image](https://user-images.githubusercontent.com/33662936/127057175-45cc339d-1db1-44dd-9192-a23d94b21c34.png)

It's in pt_BR and it stands for: The action you have requested is not allowed.

**Comment by derricksmith** [comment]
Your SAML looks correct.  This issue GLPI CSRF related:

```
 1275    /**
 1276     * Check CSRF data
 1277     *
 1278     * @since 0.84.2
 1279     *
 1280     * @param array $data $_POST data
 1281     *
 1282     * @return void
 1283    **/
 1284    static public function checkCSRF($data) {
 1285 
 1286       if (GLPI_USE_CSRF_CHECK
 1287           && (!Session::validateCSRF($data))) {
 1288          Html::displayErrorAndDie(__("The action you have requested is not allowed."), true);
 1289       }
 1290    }
```

What IDP are you using?  Is it clearing the session during the redirect?

**Comment by riccp** [comment]
I've no control over the IdP (Google) and I don't know about the session. Do you know if it happens in the IdP? Because if that is the case I cannot answer because the lack of control over it. I've just asked the team that does it at the university and as soon as they answer me I'll update here.

Thanks.

**Comment by riccp** [comment]
Update: they are using Keycloak as an  IdP and they don't know about the session. Maybe its a Keycloak issue.

**Comment by derricksmith** [comment]
Suspect configuration issue.  Reopen if you can coordinate the people managing the IdP to assist.
