### ISSUE TITLE
issue in SAML 

### ISSUE THREAD

**Issue by AmritanshuAVerma** [derricksmith/phpsaml#59]
I am unable to pinpoint the source of the issue.
![SAML](https://user-images.githubusercontent.com/40417442/126305106-2d9678c8-0828-4eec-9120-559bdcdf14e1.jpg)
![Saml2](https://user-images.githubusercontent.com/40417442/126305259-0bfe9677-dd13-4310-9032-38611f3f30cc.jpg)
![SAML3](https://user-images.githubusercontent.com/40417442/126305266-e6c77d90-940b-435c-be19-3aac169ca079.jpg)

**Comment by AmritanshuAVerma** [comment]
![image](https://user-images.githubusercontent.com/40417442/126305510-464c8128-a91f-4a27-9d65-fa285823408c.png)

**Comment by AmritanshuAVerma** [comment]
Zip of export from Firefox

**Comment by derricksmith** [comment]
Your RequestedAuthnContext response must match the request.

**Request**
```
<samlp:RequestedAuthnContext Comparison="minimum">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:X509</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

**Response**
```
<saml:AuthnStatement AuthnInstant="2021-07-20T10:20:39.893Z"
                             SessionIndex="da95fd1f-9629-43d2-9688-1013c19ce2a0::3dbaf278-94fe-4df0-af5d-a012375401d5"
                             SessionNotOnOrAfter="2021-07-20T20:20:39.893Z"
                             >
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
            </saml:AuthnContext>
</saml:AuthnStatement>
```

**Comment by AmritanshuAVerma** [comment]
i have configured it , attaching the stack trace. But still the response is invalid.
[SAML-tracer-export-2021-07-25T06 31 11.677Z.zip](https://github.com/derricksmith/phpsaml/files/6873470/SAML-tracer-export-2021-07-25T06.31.11.677Z.zip)
.

**Comment by AmritanshuAVerma** [comment]
![image](https://user-images.githubusercontent.com/40417442/127281276-8b22b2f7-4278-4184-8f0c-968245d19f71.png)
this is my configuration in GLPI Plugin

**Comment by derricksmith** [comment]
Your response is almost there but the claims are incorrect.  See the valid response below compared to your previously attached response.

**Correct**
![image](https://user-images.githubusercontent.com/7143479/131697111-d26b7427-c045-473b-8e04-480f512e3fe4.png)


**Your Response**
![image](https://user-images.githubusercontent.com/7143479/131697133-25179b27-ffbe-4300-bc6f-c07fa31f187f.png)

**Comment by derricksmith** [comment]
Closing due to no response.  Reopen if needed.
