### ISSUE TITLE
phpsaml not working with PHP 7.3

### ISSUE THREAD

**Issue by alaa-mir** [derricksmith/phpsaml#6]
This project does not support the PHP7.3 version, it generates the following error:

[Wed Oct 23 00:21:06.549024 2019] [php7:error] [pid 1977] [client 10.0.2.2:55740] PHP Fatal error:  Uncaught Error: Call to a member function item() on bool in /var/www/html/glpi/plugins/phpsaml/lib/xmlseclibs/src/XMLSecurityDSig.php:501\nStack trace:\n#0 /var/www/html/glpi/plugins/phpsaml/lib/xmlseclibs/src/XMLSecurityDSig.php(591): RobRichards\\XMLSecLibs\\XMLSecurityDSig->processRefNode(Object(DOMElement))\n#1 /var/www/html/glpi/plugins/phpsaml/lib/php-saml/src/Saml2/Utils.php(1402): RobRichards\\XMLSecLibs\\XMLSecurityDSig->validateReference()\n#2 /var/www/html/glpi/plugins/phpsaml/lib/php-saml/src/Saml2/Response.php(410): OneLogin\\Saml2\\Utils::validateSign(Object(DOMDocument), '-----BEGIN CERT...', '', 'sha1', '/samlp:Response...', NULL)\n#3 /var/www/html/glpi/plugins/phpsaml/front/acs.php(18): OneLogin\\Saml2\\Response->isValid()\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/phpsaml/lib/xmlseclibs/src/XMLSecurityDSig.php on line 501

The error is caused by the regular expression used on the xmlseclibs library in line 10 of XPath.php.
The error and fix are explained in the following link 
(https://stackoverflow.com/questions/57111993/php7-3-regex-something-went-wrong)

**Fix:**
Replace const EXTENDED_ALPHANUMERIC = '\w\d\s-_:\.';  by const EXTENDED_ALPHANUMERIC = '\w\d\s\-_:\.'; 

The fix has been added to the library (Please see https://github.com/robrichards/xmlseclibs/blob/master/src/Utils/XPath.php), this fix should be 
implemented in this project  to support PHP 7.3

**Comment by derricksmith** [comment]
I updated xmlseclibs with the latest repo.  I no longer have GLPI dev environment and cannot test.  Please confirm the latest version resolves your issue.

**Comment by derricksmith** [comment]
I loaded a dev environment with the latest version of the plugin and PHP7.3.  All is working now, so closing this issue.
