### ISSUE TITLE
Missing db table column saml_sp_nameid_format 

### ISSUE THREAD

**Issue by abelmferreira** [derricksmith/phpsaml#60]
Thanks for this plugin!! But i think theres is a little bug in plugin instalation.

I activated this plugin for the first time with the latest version 1.1.2.

But i notice that changes in field "Name ID Format " in plugin configuration dont save, keeping always unspecified, no matters the option i set.

in php console i got this error many time:
```
PHP Notice:  Undefined index: saml_sp_nameid_format in /var/www/html/plugins/phpsaml/inc/config.class.php on line 406
```
looking the code and database structure, the column name saml_sp_nameid_format in table glpi_plugin_phpsaml_configs dosnt exist.

I manualy created the column and now everythink works fine, i can now save changes in "Name ID Format " from plugin configuration page and have no more errors in PHP console.

**Comment by gtinging** [comment]
hi,
 how saml_sp_nameid_format  type is txt or varchar?

**Comment by abelmferreira** [comment]
> hi,
> how saml_sp_nameid_format type is txt or varchar?

I used varchar(128) like others column

**Comment by derricksmith** [comment]
Thanks for reporting and troubleshooting.  I'll look at the install script.  It should be varchar.

**Comment by mrgeppetto** [comment]
Any fix coming out for this? I think I'm having the same issues but I'm not too comfortable editing my database. 

> Thanks for this plugin!! But i think theres is a little bug in plugin instalation.
> 
> I activated this plugin for the first time with the latest version 1.1.2.
> 
> But i notice that changes in field "Name ID Format " in plugin configuration dont save, keeping always unspecified, no matters the option i set.
> 
> in php console i got this error many time:
> 
> ```
> PHP Notice:  Undefined index: saml_sp_nameid_format in /var/www/html/plugins/phpsaml/inc/config.class.php on line 406
> ```
> 
> looking the code and database structure, the column name saml_sp_nameid_format in table glpi_plugin_phpsaml_configs dosnt exist.
> 
> I manualy created the column and now everythink works fine, i can now save changes in "Name ID Format " from plugin configuration page and have no more errors in PHP console.

Were you also getting the cannot modify header information?

Thanks guys!

**Comment by derricksmith** [comment]
I reworked the upgrade tasks.  All upgrade tasks will fire now and check for newly added DB columns.
