### ISSUE TITLE
SSO Login Issue

### ISSUE THREAD

**Issue by MuffinAmor** [derricksmith/phpsaml#61]
Hello,
some Clients has a white site after try to login in the GLPI with SSO.
The Browser displays a error with the same site attribute of the cookie. 
Which can be the cause of the problem?

**Comment by derricksmith** [comment]
Can you provide a screenshot?  White site would indicate a PHP error.  Are there any errors in the GLPI PHP error log?

**Comment by derricksmith** [comment]
Closing due to no response.  Reopen if needed.
