### ISSUE TITLE
PHP SAML - Plugin not visible in the plugin list

### ISSUE THREAD

**Issue by kaderuk** [derricksmith/phpsaml#62]
Just configured the GLPI v9.5.5 on Ubuntu v20.04, PHP v 7.4.3, the plugin does not appear on plugin list, is there any compatibility issue?. I tried other plugins and its working fine, tried latest 2 new versions of PHP SAML. Any suggestions please.

**Comment by mrgeppetto** [comment]
When you import the "phpsaml" folder into the plugins folder in the glpi directory, did you remove the version number, i.e phpsaml-1.1.2 > phpsaml

**Comment by kaderuk** [comment]
@mrgeppetto - Thanks for your support, Yes.. it worked after renaming the folder
