### ISSUE TITLE
User or NameID not found

### ISSUE THREAD

**Issue by matheussinnis** [derricksmith/phpsaml#63]
It is generating error: "User or NameID not found". I gave you the details by email, if you can help me.

**Comment by matheussinnis** [comment]
Once authenticated, should the plugin automatically create the user in the GLPI database or do I have to create manual users (and passwords are under SAML control)?

**Comment by derricksmith** [comment]
I use ldap integration to create the user.  Then SAML for authentication.  It works well.  Otherwise, you can just create the user manually.

Sent from my iPhone

On Aug 24, 2021, at 8:32 PM, matheussinnis ***@***.***> wrote:

﻿

Once authenticated, should the plugin automatically create the user in the GLPI database or do I have to create manual users (and passwords are under SAML control)?

**Comment by mrgeppetto** [comment]
> Once authenticated, should the plugin automatically create the user in the GLPI database or do I have to create manual users (and passwords are under SAML control)?

Unfortunately there isn't any type of user provisioning. I explored around under "Other Authentication Methods" and the rules management, but I don't think the plugin interacts with it. I know with the official SSO GLPI plugin, I believe it works, but this plugin is pretty good. But on our end we don't do any ldap integration so we might be stuck manually adding users.

**Comment by derricksmith** [comment]
JIT provisioning is on the roadmap but I haven't had time to work on it.  It shouldn't be too difficult to implement.  This is how I see it working in the plugin.

1. Add a configuration option to enable JIT provisioning.
2. Add if statement to the glpiLogin method of the PluginPhpsamlPhpsaml class near line 69 to conditionally create a new user if JIT provisioning is enabled.
3.   Create the user based on email NAMEID, First Name and Last Name claims.

I haven't had the time to dig through the GLPI code to figure out the method/function for creating users.  Once I have that this should be easy to include in the next release.  If someone would be so kind to help with that function we will be much closer for this functionality.

**Comment by derricksmith** [comment]
Spent considerable time on this today.  Check JIT in PR 1.1.3.  If this works for you, I'll merge.

**Comment by matheussinnis** [comment]
I tested it and it worked correctly.
I just adjusted my side not to save password in database.
Thank you very much and congratulations!!!!!

**Comment by mrgeppetto** [comment]
> Spent considerable time on this today. Check JIT in PR 1.1.3. If this works for you, I'll merge.

Thanks for this dude, I'll test it when I get into work tomorrow. We just started using GLPI and I'm testing plugs and whatnot. When I get some time I'll try and see what I can do to help maintain this plugin.

**Comment by matheussinnis** [comment]
> No problem. Just want to confirm how you adjusted the password? I believe GLPI should create a new user with password. I create a cryptographically secure random 20 character alphanumeric key for the password. It can always be changed later but it's better than a null password.


For reasons of the "Information Security" sector, I cannot keep passwords in the GLPI database. Authentication and password data are in SAML only.

The change I made to the plugin code was to comment out these lines - https://ibb.co/HG129mL

**Comment by derricksmith** [comment]
Thanks.  I dug into this some and confirmed that GLPI creates a null database value for the password if you do not supply a password.  This is not an issue while SSO is enforced but large issue if SSO was ever turned off.
