### ISSUE TITLE
Php SAML not able to install on GLPI 9.5.6

### ISSUE THREAD

**Issue by rajesh-rengaraj** [derricksmith/phpsaml#69]
Hi Team I have try to install phpsaml on my glpi version 9.5.6 but not able to install. Please help me on this issue. Its really appreciated and am going to use google IDP for my authentication.Please help me early as possible

**Comment by Megachip** [comment]
Did you use the marketplace for install?

**Comment by derricksmith** [comment]
What error are you receiving?  The current version works with 9.5.6
