### ISSUE TITLE
Error in php-erros log -> Undefined index: noAUTO

### ISSUE THREAD

**Issue by andrepetinga** [derricksmith/phpsaml#7]
Hello.
What is this error mean? I have several of these lines in the php-erros.log file and I can't understand the problem.

[2019-11-21 11:52:27] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi-qa.ipleiria.pt/public_html/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: noAUTO
  Backtrace :
  plugins/phpsaml/setup.php:158
  inc/plugin.class.php:1129                          plugin_post_init_phpsaml()
  inc/includes.php:107                               Plugin::doHook()
  index.php:57                                       include()
  {"user":"@GLPI-DEV"}
2019-11-21 11:52:47 [4977@GLPI-DEV]
User not found.

Why the "User not found" ??

When I open the link it generates the above log, but without the last 2 lines:

2019-11-21 11:52:47 [4977@GLPI-DEV]
User not found.

These lines are written when I do the Login.

Is this an issue?

**Comment by derricksmith** [comment]
Does the user exist in GLPI?  The plugin does not perform JIT provisioning.

**Comment by derricksmith** [comment]
I've resolved the Undefined index: noAUTO issue in the test branch.  Let me know if your user error is resolved.

**Comment by andrepetinga** [comment]
It seems so. I tried to login with my user and the log registered:

2020-10-12 15:07:59 [5647@GLPI-DEV]
User not found.

Them I replaced the plugin, and after my login, nothing new in the log file 👍
