### ISSUE TITLE
update 1.1.3

### ISSUE THREAD

**Issue by oeric-A2B** [derricksmith/phpsaml#70]
Hello,
first of all, excuse me for my english. I'm trying to configure version 1.1.2, but I'm having some problems. either a blank page or "Invalid SAML Response". So I allow myself to ask you if version 1.1.3 is published? Thank you

**Comment by lupin3rd** [comment]
Version 1.1.3 will be avaible in GLPI 10.0.0 version ?
Any news about the release date?
Thank you.

**Comment by borkie** [comment]
Any news about version 1.1.3 for GLPI 10?
Thank you

**Comment by derricksmith** [comment]
Happy to help troubleshoot your issue.  Can you provide some screenshots of the errors/output and your phpsaml configuration page and your IDP configuration for GLPI?  Obfuscate as necessary.

> Version 1.1.3 will be avaible in GLPI 10.0.0 version ? Any news about the release date? Thank you.

Working on newest version with fixes for 9.5.7.  I won't test with 10.0 until it has been officially released.
