### ISSUE TITLE
Enforced option make glpi cli unusable

### ISSUE THREAD

**Issue by Dimitri281** [derricksmith/phpsaml#71]
Hello,

i have recently an issue with the plugin PHP SAML on GLPI 9.5.7,
i give you the link to the glpi issue : https://github.com/glpi-project/glpi/issues/11167#event-6352169456 

when the option enforced of PHP SAML was Enabled the bin/console of glpi not working.

the solution for use the cli is :
`php /var/www/html/glpi/bin/console  --no-plugins`

for desactivate the plugin during the run of console instance.

TIA,
Dimitri

**Comment by derricksmith** [comment]
I started on 1.2.0 and have a fix for this issue.  I have a couple of other changes to make but should have this finished by next week.

**Comment by Dimitri281** [comment]
Hi, 
Thanks you.
:)
