### ISSUE TITLE
Issue on multi-tenant Azure login 

### ISSUE THREAD

**Issue by nykroy** [derricksmith/phpsaml#72]
hi 
I have a problem that i dont know if is a bug 

If i login with a user of my organization it is works perfectly but if i login with other tenant than have permisións to login this is the error that i see

![image](https://user-images.githubusercontent.com/7745881/161753751-edb5ffda-11f8-4726-9226-ad0a8dec0bbd.png)

![image](https://user-images.githubusercontent.com/7745881/161753851-ac979414-9d9c-4983-a37c-fc8f4b53bb52.png)

sorry for my english

**Comment by derricksmith** [comment]
I think I understand.  Need to see the contents of the SAML responses.  Can you expand the orange SAML GET and POST requests in your screenshot and post back here?  Be sure to obfuscate confidential info.

**Comment by nykroy** [comment]
GET:
![image](https://user-images.githubusercontent.com/7745881/162381872-859c38e7-103c-4ba2-91f6-6a9c20838c5e.png)
![image](https://user-images.githubusercontent.com/7745881/162382184-ef8a6339-6cc0-454e-9134-4323919272a5.png)

POST:
![image](https://user-images.githubusercontent.com/7745881/162382606-9bf79a72-8b54-4ec6-be91-613ed2f43429.png)
![image](https://user-images.githubusercontent.com/7745881/162382785-9fbc72e1-a555-43df-83c9-51a3eeed4e9f.png)

**Comment by nykroy** [comment]
there are any option to add more entries on db with other saml applicacions form azure?. I see the plugin take de ID 1 on the config.class.php por conection with the db and take de dates for make de sso and maybe i can add another line for another tenant. 
![image](https://user-images.githubusercontent.com/7745881/162441248-01e4d5f9-bb8b-4e9b-bf2f-ea8bb78b3ba2.png)

**Comment by nykroy** [comment]
I  select an Name Id Format but when i save allwais is select unespecified
![image](https://user-images.githubusercontent.com/7745881/163953294-6aa2861f-5deb-4217-8d9a-8667516cd5f2.png)

I see on db that this is not a field of database
![image](https://user-images.githubusercontent.com/7745881/163953543-25e3014b-f579-48dc-a406-6927054e77b1.png)

It is possible that these is the reason for my problem?

**Comment by derricksmith** [comment]
I started working on version 1.2.0.  The issue where name_id_format column is missing will be fixed.

**Comment by nykroy** [comment]
i Know, on the issue https://github.com/derricksmith/phpsaml/issues/74 but on my case i have created this field on de database. Now y can select de email address like NameId but the issue persist

**Comment by derricksmith** [comment]
Just want to make sure I understand.  After you created the field, you are still unable to save the value when changing the field on the form?

**Comment by nykroy** [comment]
No, After i created the field i receive the same response on login with external Azure AD
![image](https://user-images.githubusercontent.com/7745881/164388617-fd0f0770-0b9e-4fb1-8e75-5326bc734c95.png)
Both Azure AD, mine and my client have the respective App for comunication between them. I have the enterprise app on my Azure AD and another app link with the enterprise App for link with my client Azure AD.
