### ISSUE TITLE
Marketplace / Not available for GLPI 9.5.7

### ISSUE THREAD

**Issue by Ianooch** [derricksmith/phpsaml#73]
Hello,

Is there an actual limitation or is this a bug ?
![image](https://user-images.githubusercontent.com/103424940/162729053-2915a841-2ff0-4a7d-814b-5fa8e2758454.png)

Thanks !

**Comment by derricksmith** [comment]
Not really a bug.  Just haven't released a new version of the plugin.  I am working on 1.2.0 and testing against 1.5.7 without issue.  Should be released shortly.

**Comment by champakakumara** [comment]
I have same issues ,Marketplace show error " this plugin is not available for your glpi version" .any other method to install plugin? 21/04/20222

**Comment by derricksmith** [comment]
> I have same issues ,Marketplace show error " this plugin is not available for your glpi version" .any other method to install plugin? 21/04/20222

This is because I have not released the latest version to GLPI marketplace yet.  You can download the 1.2.0 branch from GitHub.

**Comment by XabierMoureP** [comment]
Hi
I'm having problems when trying to install from the branch. What I have done is downloading the source code from https://github.com/derricksmith/phpsaml/archive/refs/tags/1.1.2.tar.gz and uncompressing it in the /plugins folder. The problem with this is that when I go to plugins in GLPI, I can't find it, therefore I'm not being able to install the plugin. Am I doing  something wrong?
Thanks in advance :)

**Comment by derricksmith** [comment]
Make sure the plug-in folder name is "phpsaml".  I've been busy but should be able to finish up 1.2.0 soon and will update marketplace.
