### ISSUE TITLE
Undefined saml_sp_nameid_format 

### ISSUE THREAD

**Issue by tric78** [derricksmith/phpsaml#74]
Hi, congrats for your plugin! I have a question:

getting this error every minute in the log:

[2022-04-12 15:39:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "saml_sp_nameid_format" in /var/www/glpi/plugins/phpsaml/inc/config.class.php at line 406
 
In the plugin UI configuration there is a field to choose between Undefined-Email-Transient-Persistent, but if try to set it up the changes are not saved.

I have checked and in the database plugin's table ([glpi_plugin_phpsaml_configs]) does not exist the field "saml_sp_nameid_format" reffered in line 406!

How can i set this config to avoid the log full?

thanks!!

**Comment by nykroy** [comment]
If you create the column solved the problem
