### ISSUE TITLE
Not support for GLPI 9.5.7

### ISSUE THREAD

**Issue by champakakumara** [derricksmith/phpsaml#78]
Not support for GLPI 9.5.7

**Comment by champakakumara** [comment]
Marketplace show error " this plugin is not available for your glpi version"

**Comment by champakakumara** [comment]
I upload manually phpsalm 1.1.3 to glpi plugin folder and after update Version 1.2.0  files manually (hook.php, install/update.class.php, setup.php) but now glpi plugin page not loaded error "This page isn’t workingfixedassets.mggroup.lk is currently unable to handle this request.
HTTP ERROR 500"

**Comment by derricksmith** [comment]
What do your php logs say?

**Comment by champakakumara** [comment]
PHP Fatal error:  Cannot redeclare plugin_version_phpsaml() (previously declared in /var/www/html/marketplace/phpsaml-1.1.2/setup.php:51) in /var/www/html/plugins/phpsaml-1.1.3/setup.php on line 48, referer: https://URL/front/setup.auth.php

**Comment by derricksmith** [comment]
You can't have the the plug-in loaded through marketplace and in the plug-in folders.  Cannot redeclare same class names.  Suggest removing both and reinstalling 1.2.0 from the GitHub  branch only.

**Comment by champakakumara** [comment]
Thanks now its installed. is it support for Google? I got Error: app_not_configured_for_user

Service is not configured for this user.

**Comment by derricksmith** [comment]
Many people have this working with google idp.  I don't have google so can't speak to the correct configuration but SAML is fairly similar across idps.

**Comment by champakakumara** [comment]
Hi derricksmith

Thanks your reply 
SAML App ACS URL and Entity ID I must provide to Google. do you have any idea about that?
