### ISSUE TITLE
Does not save changes

### ISSUE THREAD

**Issue by gustavo1321** [derricksmith/phpsaml#79]
Hello, thank you all for the input, I have a question.. has it happened to them that at the time of saving the configuration, return to central and do not save the changes?  I was doing some research and something appeared regarding a table, but I checked and the table exists, the strange thing is that it does not report logs of any error.

**Comment by derricksmith** [comment]
Version?

**Comment by gustavo1321** [comment]
Version 9.5.7, I did an update to 9.5.4

**Comment by icttpzgithub** [comment]
Hi Derrick, 
I seem to be having the same problem.
I fill in the form (config.php) and click update at the bottom, but it just returns me back to the blank form, nothing has been saved.
Any ideas?
I've tried with both FF and chrome
phpsaml1.2.0; glpi 10.0.0; Ubuntu 20.04 LTS (I know I'm using unsupported versions)
Kind regards
DP

**Comment by icttpzgithub** [comment]
If I manually create the entry in the table
 INSERT INTO `glpi_plugin_phpsaml_configs` (`id`,`version`, `enforced`, `strict`, `debug`, `jit`, `saml_sp_certificate`, `saml_sp_certificate_key`, `saml_sp_nameid_format`, `saml_idp_entity_id`, `saml_idp_single_sign_on_service`, `saml_idp_single_logout_service`, `saml_idp_certificate`, `requested_authn_context`, `requested_authn_context_comparison`)
    -> VALUES ('1', '1.2.0', '0', '1','0','1', '', '', '', .blah, blah, blah.
Then afterwards modifying the values via the config.php is working fine.

**Comment by derricksmith** [comment]
The new version puts all the phpsaml logs into a file called phosaml in the _logs directory of glpi.  Can you upload that file?

**Comment by icttpzgithub** [comment]
sure, here you go:-

[phpsaml.log](https://github.com/derricksmith/phpsaml/files/8632288/phpsaml.log)

**Comment by derricksmith** [comment]
Suggest removing plugin and installing latest version 1.2.0 from Github

**Comment by derricksmith** [comment]
Can you check the database and let me know what columns exist in the phpsaml plugin table?

**Comment by jviadair** [comment]
Hi,

I have the same problem. I cannot setup the phpSAML settings via the GUI, I inserted them via SQL

This is the name of columns exist in the phpsaml plugin table:
id
version 
enforced
strict
debug
jit
saml_sp_certificate
saml_sp_certificate_key
saml_sp_nameid_format
saml_idp_entity_id
saml_idp_single_sign_on_service
saml_idp_single_logout_service
saml_idp_certificate
requested_authn_context
requested_authn_context_comparison
saml_security_nameidencrypted
saml_security_authnrequestssigned
saml_security_logoutrequestsigned
saml_security_logoutresponsesigned

**Comment by WilliamDR35** [comment]
Hello, i'm having the same issue. Can someone detail how to fix it please ?

**Comment by derricksmith** [comment]
Issue was resolved in #106 

Can you confirm

**Comment by WilliamDR35** [comment]
It's working, thank you !
