### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by enannos** [derricksmith/phpsaml#8]
Hi,

I am currently using GLPI 9.4.6 and found out about your plugin by searching for a SSO solution.
How can I use your plugin in an MS AD environment?

Thank you

**Comment by derricksmith** [comment]
I added instructions to the readme.  Are you trying to configure with ADFS or AD LDAP?

**Comment by enannos** [comment]
I am using AD LDAP also but I cannot find out how to work with the plugin.

**Comment by derricksmith** [comment]
This plugin only performs authentication.  The user object must exist in GLPI before authentication can work.  You can use LDAP integration in GLPI to populate the user and then use this plugin to authenticate using an SSO provider, such as Azure AD, Okta, Onelogin, etc.

**Comment by lordkey-II** [comment]
Can i create manual user and use your plugin to authenticate? I use Google as IDP, i need to map attributes? If yes, what attributes?

**Comment by derricksmith** [comment]
Yes, you can prepopulate local users or use the ldap integration.  Then use Google IDP to SSO using the email as the name identifier.  No other attributes are mapped.
