### ISSUE TITLE
Not able to install the plugin on the GLPI 10.0.1 

### ISSUE THREAD

**Issue by rajesh-rengaraj** [derricksmith/phpsaml#86]
Hi, derrick smith phpsaml plugin cannot install in GLPI 10.0.1. Please help me with this issue.

**Comment by oswalvas** [comment]
Hello, I also have the same issue.

**Comment by alessandrocaetanob** [comment]
Download the branch [1.2.0](https://github.com/derricksmith/phpsaml/tree/Version-1.2.0) and change the function `plugin_phpsaml_check_prerequisites` on `setup.php` line 68 from:

```
function plugin_phpsaml_check_prerequisites()
{

    if (version_compare(GLPI_VERSION, '9.4', 'lt') || version_compare(GLPI_VERSION, '10.0.0', 'gt')) {
        echo "This plugin requires GLPI >= 9.4 and GLPI <= 10.0.2";
        return false;
    }

    return true;
}
```

To

```
function plugin_phpsaml_check_prerequisites()
{

    if (version_compare(GLPI_VERSION, '9.4', 'lt') || version_compare(GLPI_VERSION, '10.0.2', 'gt')) {
        echo "This plugin requires GLPI >= 9.4 and GLPI <= 10.0.2";
        return false;
    }

    return true;
}
```

**Comment by swalker-aup** [comment]
Hi Derrick,

I only see branch 1.2 listed (https://github.com/derricksmith/phpsaml/branches), but you've mentioned branch 1.3.  Am I missing something?

Thanks for all the work you do on this project!

**Comment by rajesh-rengaraj** [comment]
Hi Derricksmith,

First of all thanks for the reply. I really appreciate your help As per your suggestions I have made the changes in the plugin. But during the installation am receiving the below error. Please help me with this issue.


error populate glpi_plugin_phpsaml_configs Incorrect integer value: '' for column `glpi`.`glpi_plugin_phpsaml_configs`.`jit` at row 1 

Regards,

Rajesh R
Network Team 
Mallow Technologies Private Limited

**Comment by b0n0is** [comment]
> Download the branch [1.2.0](https://github.com/derricksmith/phpsaml/tree/Version-1.2.0) and change the function `plugin_phpsaml_check_prerequisites` on `setup.php` line 68 from:
> 
> ```
> function plugin_phpsaml_check_prerequisites()
> {
> 
>     if (version_compare(GLPI_VERSION, '9.4', 'lt') || version_compare(GLPI_VERSION, '10.0.0', 'gt')) {
>         echo "This plugin requires GLPI >= 9.4 and GLPI <= 10.0.2";
>         return false;
>     }
> 
>     return true;
> }
> ```
> 
> To
> 
> ```
> function plugin_phpsaml_check_prerequisites()
> {
> 
>     if (version_compare(GLPI_VERSION, '9.4', 'lt') || version_compare(GLPI_VERSION, '10.0.2', 'gt')) {
>         echo "This plugin requires GLPI >= 9.4 and GLPI <= 10.0.2";
>         return false;
>     }
> 
>     return true;
> }
> ```
> 
> This will allow it to be installed on GLPI versions `9.4` to `10.0.2` with no problems.

Hi Alessandro, 
I did that some days ago, and it doesn't work for me, GLIP stop working can't reach the web application
I had to disable the plugin by the CLI
and when I check the status I have this error: 
![2022-07-05 15_13_34-Remote Desktop Manager Free  PPSUPPORT](https://user-images.githubusercontent.com/82151679/177336223-b31dbe0f-1d70-4203-ac09-337eb955da67.png)

thanks

**Comment by breno404** [comment]
Hi guys, I changed the code locally

Summary:
In ./front/config.php
Search for "$phpSamlConfig->showForm()" and replace for "$phpSamlConfig->showForm($_POST["id"])"

In ./front/config.form.php
Search for "$phpsamlconf->showForm()" and replace for "$phpsamlconf->showForm($_POST["id"])"

In ./inc/config.class.php
Search for "function showForm()" and replace for "function showForm($ID, array $options = [])"

This worked for me.

**Comment by rajesh-rengaraj** [comment]
Hi Derricksmith,

I have tried your updated plugin Phpsaml 1.2.1 with glpi version 10. But am I not able to save the settings. Please help me on this issue.    

Regards,

Rajesh R
Network Team 
Mallow Technologies Private Limited

**Comment by derricksmith** [comment]
> Sorry @b0n0is, I forgot to include something @derricksmith commented on issue #75. For the plugin to work, you have the change line 53 on the file ` inc/config.class.php` from:
> 
> `function showForm(){`
> 
> to:
> 
> `function showForm($ID, array $options = []) {`

This change is included in 1.2.1

**Comment by derricksmith** [comment]
> Sorry @b0n0is, I forgot to include something @derricksmith commented on issue #75. For the plugin to work, you have the change line 53 on the file ` inc/config.class.php` from:
> 
> `function showForm(){`
> 
> to:
> 
> `function showForm($ID, array $options = []) {`

This is included in Version 1.2.1

**Comment by alessandrocaetanob** [comment]
Nice! That's even better, so people just need to download the version from the new branch :)

**Comment by derricksmith** [comment]
Fixed on line 22 of update.class.php in Version 1.2.1.  Added is_array($array) to conditional.

Test and let me know if you still receive an error.

**Comment by b0n0is** [comment]
installation done without problem on php 8.1 
got an error with php7.4 but plugin installed and activated 
![image](https://user-images.githubusercontent.com/82151679/180750478-b68604f3-b44b-4979-b9fb-040eb31c0094.png)

I have another issue, I can't update the configuration

**Comment by Ketchup31** [comment]
Same for me than @b0n0is. I cannot save the configuration. 
PHP 7.4.20
GLPI 10.0.0.2
phpsaml:  1.2.1

**Comment by derricksmith** [comment]
What columns are in the phpsaml plugin table?
