### ISSUE TITLE
Invalid array settings: idp_entityId_not_found, idp_sso_not_found, idp_cert_or_fingerprint_not_found_and_required [AZURE]

### ISSUE THREAD

**Issue by r1card0sl** [derricksmith/phpsaml#91]
‎I fill in the form fields in the plugin configuration, but when I try to login, I get the message this image error:

I use Azure SAML.0

![image](https://user-images.githubusercontent.com/108961497/179305724-a37426eb-ff36-4d7f-b0ff-e5ba10b0b8d5.png)

**Comment by derricksmith** [comment]
Did you upgrade from a previous version of phpsaml plugin?  What columns are in the phpsaml plugin table in the database?

**Comment by r1card0sl** [comment]
Yes. I updated from an earlier version of the plugin.

The table has the following columns:
- id (primary key);
- version;
- enforced;
- strict;
- debug;
- jit;
- saml_sp_certificate;
- saml_sp_certificate_key;
- saml_sp_nameid_format;
- saml_idp_entily_id;
- saml_idp_single_sign_on_service;
- saml_idp_single_logout_service;
- saml_idp_certificate;
- requested_authn_context;
- requested_authn_context_comparison;
- saml_security_nameidencrypted;
- saml_security_authnrequestssigned;
- saml_security_logoutrequestssigned;
- saml_security_logoutresponsessigned.

**Comment by WilliamDR35** [comment]
Hello. I have the same issue with GLPI 10.0 on debian 11when trying to authentificate with azure AD.

Even after filling the plugin configuration i get "**Invalid array settings: idp_entityId_not_found, idp_sso_not_found, idp_cert_or_fingerprint_not_found_and_required**"

**The error.log** :
PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/glpi/src/DBmysql.php on line 331, referer: https://glpi.proxy.net/
PHP Warning:  Declaration of PluginPhpsamlConfig::showForm() should be compatible with CommonDBTM::showForm($ID, array $options = Array) in /var/www/html/glpi/plugins/phpsaml/inc/config.class.php on line 53, referer: https://glpi.proxy.net/?SSO=1

Can you help me about that please ?

**Comment by derricksmith** [comment]
Issue was resolved in https://github.com/derricksmith/phpsaml/pull/106

Can you confirm

**Comment by WilliamDR35** [comment]
It's working perfectly fine, thank you !
