### ISSUE TITLE
JIT is not applying Authorizations assignment rules

### ISSUE THREAD

**Issue by DonutsNL** [derricksmith/phpsaml#97]
Currently the JIT is ignoring the Authorizations assignment rules and will create the user using glpi default rules in the root entity with the default profile.

Ldap rules are just that, designed for ldap sync.

**Comment by DonutsNL** [comment]
Maybe it is required to call $user->applyRightRules() after creation. Didnt fully review the method in the user class.

**Comment by DonutsNL** [comment]
applyRightRules require some ldap specifics. Going to do some tests to see if this method is usable.

**Comment by derricksmith** [comment]
Thanks for your work on this one!

**Comment by DonutsNL** [comment]
callstack:
1. user->Add() defined in CommonDBTM.
2. CommonDBTM calls $this->post_addItem();
3. post_addItem() is overloaded in user class;
4. user->addItem() calls user->applyRightRules()
5. user->applyRightRules evaluates both input (defined in CommonDBTM->add()) and fields.

**Comment by DonutsNL** [comment]
1. user->getFromLdap() is populating the rules to be processed;
2. Important: rules should not be processed on slave databases; validate: !$DB->isSlave() user.class.php:1634
3. new RuleRightCollection is initiated; user.class.php:1636
4. RuleRightCollection->processAllRules() is called; user.class.php:1647
5. RuleRightCollection->processAllRules() is defined in rulecollection.class.php:1474

**Comment by Ketchup31** [comment]
Also interested by this feature. Thank you for the great job and support !!!

**Comment by DonutsNL** [comment]
There is some documentation but its not up to date. https://glpi-developer-documentation.readthedocs.io/en/master/devapi/rules.html

Am in the process of applying these rules and backwards engineer a bit 😅

**Comment by Ketchup31** [comment]
Ok .. We believe in you :crossed_fingers:

**Comment by DonutsNL** [comment]
**Update:** 
Its kinda frustrating. 

I have the rules interface working but its not matching the criteria correctly and is not updating the user object as a result. 

@derricksmith is it oké to upload the sources for the rules engine. I think i can use some help in getting the created rules to match. Testing the rule in the interface works as expected. The update will introduce a rules conf option that allowes rules to be created in a saml sub_type. 

![image](https://user-images.githubusercontent.com/97617761/188237690-883c511f-fdd8-483e-b7ca-e61a937e28e3.png)
![image](https://user-images.githubusercontent.com/97617761/188237828-b444db8f-605d-495d-bff3-4a07deac726c.png)

**Comment by derricksmith** [comment]
I'm not super familiar with the rules workflow.  Can you create a PR so I can see what you want to add?

**Comment by derricksmith** [comment]
I created a branch called Rules Engine.  If its easier for you, just send the files over to derricksmith01@msn.com and I'll upload to the branch.

**Comment by DonutsNL** [comment]
created a pull request with the changes made : https://github.com/derricksmith/phpsaml/pull/116

Its possible to create PHPSaml rules in the GLPI interface.
![image](https://user-images.githubusercontent.com/97617761/204004015-ebd30c45-2a6b-47de-b838-6fe0ac0d1e05.png)
![image](https://user-images.githubusercontent.com/97617761/204004149-e2404044-d08a-4496-9d03-44bb4c0ddb86.png)

I created a testscript in the branch to test these rules. 
It reports that the rule is matched correctly and it is applying the rules. 
![image](https://user-images.githubusercontent.com/97617761/204003835-2cb35b02-4ca6-4a5b-92d7-421a0d956ce2.png)

The problem is that the rules are in fact not applied (when validating).
![image](https://user-images.githubusercontent.com/97617761/204004445-ca017729-46bb-4dbc-873d-cfdf41c90ae4.png)

No error is generated. 
I was about to start tracing the database for update statements and see what (if anything) is happening.

**Comment by DonutsNL** [comment]
As i expected, its is not performing the update action. Im not sure why. 
![image](https://user-images.githubusercontent.com/97617761/204027099-1ecfd30b-38f4-4155-83b5-c4a01211b5a3.png)

**Comment by DonutsNL** [comment]
A hook is performed on the plugin's ruleright.class.php method executeActions($output, $params, array $input = []) {  }, it seems that we need to implement the updates our self's.

**Comment by DonutsNL** [comment]
@derricksmith, I am sure I am missing something important 😅 

The rules that need to be applied are getting lost during the 'doHook()' thats being called in the rule.php->process method. See debug trace screenshots below. 

**Any ideas?**


![image](https://user-images.githubusercontent.com/97617761/204142870-9cc36b8b-b7e4-46a3-ae57-6b5ca93bef2e.png)
![image](https://user-images.githubusercontent.com/97617761/204142878-2ab81897-b030-46a8-b920-0752890370fb.png)
![image](https://user-images.githubusercontent.com/97617761/204142884-d92b2dd8-75ea-407d-ae3e-84c81ac2542b.png)
![image](https://user-images.githubusercontent.com/97617761/204142893-273b5a6f-7ea6-46a6-9e04-ebc5e951286d.png)

**Comment by LaurDaniel** [comment]
Hi @DonutsNL,
Did you find a solution on this?
Thanks!
