### ISSUE TITLE
Problem to install plugin

### ISSUE THREAD

**Issue by bcsecurityco** [derricksmith/phpsaml#98]
Hello, I have problem when i tried to install GLPI plugin on version 9,5. I tried different versions from 1.1.12 to last one of this plugins, but my GLPI didn't allowed me to install it. which version is compatible with glpi 9.5?

**Comment by b0n0is** [comment]
Hello, 
I running 1.1.1 on glpi 9.5.7

**Comment by bcsecurityco** [comment]
Hello, thank you. I will test it this week and i will give you my feedback. Thank you. What version is compatible with glpi 10.0.2, i tried the last version of this plugin but i got error when i tried to install

**Comment by derricksmith** [comment]
You should run the latest version.  See 1.2.1 branch

**Comment by sefirosweb** [comment]
@derricksmith I have same issue with branch 1.2.1 
I'm running GLPI 10.0.2

![image](https://user-images.githubusercontent.com/20754836/186141585-20a5b8e1-a2f0-4d74-bc8a-d723bb2d924e.png)

Afther the error i can access to panel to edit configuration but i can't save the keys
